"""Focused tests for the stochastic Ensemble Kalman Filter (loop 163).

Covers the new ``run_enkf`` and ``EnKFConfig`` against the same small synthetic
case used by the EKF/UKF/AUKF/PUKF/DMC tests, so the perturbed-observation
ensemble recursion is exercised cheaply on every run. The EnKF is the
Monte-Carlo ensemble comparator added to close the Ensemble-Kalman-family
exclusion risk; these tests pin its structural behaviour:

* shapes, finiteness, and the ensemble-spread diagnostics;
* bit-for-bit reproducibility for a fixed seed (the recursion is stochastic but
  seeded);
* Monte-Carlo stability -- two independent large ensembles agree closely, so the
  finite-ensemble sampling error shrinks as the ensemble grows;
* a symmetric positive-semidefinite ensemble covariance at every step;
* order-of-magnitude agreement with the UKF posterior mean on a benign case,
  confirming the EnKF is a genuine Bayesian filter and not a strawman.
"""

from __future__ import annotations

import sys
import unittest
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from gnn_state_estimation.coordinates import StationGeometry, line_of_sight_measurement
from gnn_state_estimation.dynamics import rk4_step
from gnn_state_estimation.filters import (
    EnKFConfig,
    UKFConfig,
    run_enkf,
    run_ukf,
)


def _synthetic_case() -> dict[str, np.ndarray]:
    """A short, *physically consistent* synthetic tracking case.

    Unlike the static-state cases used by the cheaper EKF/UKF reduction tests,
    the EnKF sanity checks need measurements that are consistent with the
    propagated orbital dynamics (the EnKF compares its forecast ensemble to the
    data), so the ground truth is generated by propagating the same compact
    two-body+J2+drag flow the filters use and the measurements are sampled from
    that trajectory with a fixed-seed noise draw.
    """
    stations = (
        StationGeometry(name="S0", lat_deg=35.0, lon_deg=-120.0, alt_m=100.0, min_elevation_deg=-90.0),
        StationGeometry(name="S1", lat_deg=-25.0, lon_deg=27.0, alt_m=1500.0, min_elevation_deg=-90.0),
    )
    t_len = 12
    dt = 20.0
    times_s = np.arange(t_len, dtype=np.float64) * dt
    x0 = np.array(
        [6_900_000.0, 1_200_000.0, 1_400_000.0, -950.0, 7_350.0, 750.0], dtype=np.float64
    )
    states = np.zeros((t_len, 6), dtype=np.float64)
    states[0] = x0
    for k in range(1, t_len):
        states[k] = rk4_step(
            states[k - 1], dt=dt, ballistic_coeff_m2_per_kg=0.018, t_s=float(times_s[k - 1])
        )
    meas_std = np.array([30.0, 0.02 * np.pi / 180.0, 0.02 * np.pi / 180.0, 0.08])
    measurements = np.zeros((t_len, len(stations), 4), dtype=np.float64)
    visibility = np.zeros((t_len, len(stations)), dtype=np.float64)
    rng = np.random.default_rng(0)
    for t in range(t_len):
        for s_idx, station in enumerate(stations):
            z, _vis = line_of_sight_measurement(states[t], station, float(times_s[t]))
            measurements[t, s_idx] = z + rng.normal(0.0, meas_std)
            visibility[t, s_idx] = 1.0 if (t >= 1 and (t + s_idx) % 2 == 0) else 0.0
    x0_est = x0 + np.array([1500.0, -1200.0, 900.0, 3.0, -2.5, 1.5], dtype=np.float64)
    return {
        "measurements": measurements,
        "visibility": visibility,
        "times_s": times_s,
        "stations": stations,
        "meas_std": meas_std,
        "x0_est": x0_est,
        "true_state": states[-1],
        "states": states,
    }


def _run(case: dict[str, np.ndarray], cfg: EnKFConfig):
    return run_enkf(
        measurements=case["measurements"],
        visibility=case["visibility"],
        times_s=case["times_s"],
        stations=case["stations"],
        ballistic_coeff_m2_per_kg=0.018,
        meas_std_vector=case["meas_std"],
        x0_est=case["x0_est"],
        cfg=cfg,
    )


class EnKFTests(unittest.TestCase):
    def test_returns_finite_state_and_diagnostics(self) -> None:
        case = _synthetic_case()
        cfg = EnKFConfig(ensemble_size=48, seed=11)
        x_hist, p_hist, diag = _run(case, cfg)
        t_len = case["measurements"].shape[0]
        self.assertEqual(x_hist.shape, (t_len, 6))
        self.assertEqual(p_hist.shape, (t_len, 6, 6))
        self.assertTrue(np.all(np.isfinite(x_hist)))
        self.assertTrue(np.all(np.isfinite(p_hist)))
        self.assertEqual(diag["ensemble_size"], 48)
        self.assertIn("pos_spread_m", diag)
        self.assertEqual(diag["pos_spread_m"].shape, (t_len,))
        self.assertTrue(np.all(np.isfinite(diag["pos_spread_m"])))
        # The initial ensemble spread should be of order the initial position
        # std (2000 m default), not collapsed or exploded.
        self.assertGreater(diag["pos_spread_m"][0], 100.0)

    def test_deterministic_given_seed(self) -> None:
        """The recursion is stochastic but seeded: identical seeds reproduce
        the filtered path exactly."""
        case = _synthetic_case()
        cfg = EnKFConfig(ensemble_size=32, seed=2024)
        x_a, p_a, _ = _run(case, cfg)
        x_b, p_b, _ = _run(case, cfg)
        self.assertTrue(np.array_equal(x_a, x_b))
        self.assertTrue(np.array_equal(p_a, p_b))

    def test_seed_changes_realization(self) -> None:
        case = _synthetic_case()
        x_a, _, _ = _run(case, EnKFConfig(ensemble_size=32, seed=1))
        x_b, _, _ = _run(case, EnKFConfig(ensemble_size=32, seed=2))
        self.assertFalse(np.array_equal(x_a, x_b))

    def test_monte_carlo_stability_large_ensemble(self) -> None:
        """Two independent large ensembles should produce nearly the same
        posterior mean: finite-ensemble sampling error shrinks with N."""
        case = _synthetic_case()
        x_a, _, _ = _run(case, EnKFConfig(ensemble_size=800, seed=101))
        x_b, _, _ = _run(case, EnKFConfig(ensemble_size=800, seed=202))
        # Position agreement well below the 1500 m initial perturbation scale
        # (the N=800 two-seed gap on this case is ~115 m; 350 m leaves margin).
        max_pos_gap = float(np.max(np.abs(x_a[:, :3] - x_b[:, :3])))
        self.assertLess(max_pos_gap, 350.0, f"large-ensemble means disagree by {max_pos_gap} m")

    def test_covariance_symmetric_psd(self) -> None:
        case = _synthetic_case()
        _, p_hist, _ = _run(case, EnKFConfig(ensemble_size=64, seed=7))
        for k in range(p_hist.shape[0]):
            p = p_hist[k]
            self.assertTrue(np.allclose(p, p.T, atol=1e-6), f"P[{k}] not symmetric")
            eig_min = float(np.min(np.linalg.eigvalsh(0.5 * (p + p.T))))
            self.assertGreater(eig_min, -1e-6, f"P[{k}] not PSD (min eig {eig_min})")

    def test_tracks_ukf_order_of_magnitude(self) -> None:
        """A large-ensemble EnKF and the UKF see the same data and the same
        compact model; their posterior means should agree to within a modest
        fraction of the orbit scale (the EnKF is a real Bayesian filter)."""
        case = _synthetic_case()
        enkf_cfg = EnKFConfig(
            q_pos_m=4.0,
            q_vel_mps=0.04,
            init_pos_std_m=2e3,
            init_vel_std_mps=5.0,
            ensemble_size=1000,
            seed=303,
        )
        ukf_cfg = UKFConfig(q_pos_m=4.0, q_vel_mps=0.04, init_pos_std_m=2e3, init_vel_std_mps=5.0)
        x_enkf, _, _ = _run(case, enkf_cfg)
        x_ukf, _ = run_ukf(
            measurements=case["measurements"],
            visibility=case["visibility"],
            times_s=case["times_s"],
            stations=case["stations"],
            ballistic_coeff_m2_per_kg=0.018,
            meas_std_vector=case["meas_std"],
            x0_est=case["x0_est"],
            cfg=ukf_cfg,
        )
        # On consistent data the large-ensemble EnKF tracks the UKF to ~60 m on
        # this case; 500 m is a comfortable bound that still rejects divergence.
        max_pos_gap = float(np.max(np.abs(x_enkf[:, :3] - x_ukf[:, :3])))
        self.assertLess(max_pos_gap, 500.0, f"EnKF/UKF posterior gap {max_pos_gap} m")
        # The EnKF must actually use the measurements: its final-step position
        # error should be well below the initial-perturbation scale.
        init_pos_err = float(np.linalg.norm(case["x0_est"][:3] - case["states"][0, :3]))
        final_pos_err = float(np.linalg.norm(x_enkf[-1, :3] - case["true_state"][:3]))
        self.assertLess(final_pos_err, 0.6 * init_pos_err, "EnKF did not converge from x0")


if __name__ == "__main__":  # pragma: no cover
    unittest.main()
