#!/usr/bin/env python3
"""Active main-manuscript table/figure regeneration check.

This command is intentionally evidence-bounded. It regenerates active
``paper/main.tex`` table and figure artifacts from already-materialized result
artifacts, compares the generated bytes with the current paper artifacts, and
records precise differences when they do not match. It does not rerun raw-data
simulation, estimator training, filter estimation, or live public-data fetches.

Outputs:
    results/validation/active_manuscript_regeneration.json
    results/validation/active_manuscript_regeneration.md
"""
from __future__ import annotations

import argparse
import datetime as dt
import difflib
import hashlib
import importlib.util
import json
import os
import shutil
import sys
import tempfile
from pathlib import Path
from typing import Any, Callable

os.environ.setdefault("MPLBACKEND", "Agg")

ROOT = Path(__file__).resolve().parents[1]
PAPER = ROOT / "paper"
RESULTS = ROOT / "results"
VALIDATION = RESULTS / "validation"
RELEASE_PACKET = RESULTS / "release_packet.json"

SCOPE_BOUNDARY = (
    "Regenerates active paper/main.tex table/figure artifacts from materialized "
    "repository result artifacts only; does not claim full raw-data, "
    "model-training, filter-estimation, live-public-data, or independent "
    "end-to-end reproduction outside the supplied archive."
)

ACTIVE_TABLE_SOURCES: dict[str, list[str]] = {
    "paper/tables/main_abbreviation_glossary.tex": [],
    "paper/tables/main_framework_portability.tex": [],
    "paper/tables/main_findings_summary.tex": [
        "results/force_model_mismatch_adaptation_summary.json",
        "results/force_mismatch_seed_significance.json",
        "results/drag_scale_constructive_positive_control/drag_scale_constructive_positive_control.json",
        "results/drag_scale_ukf_constructive_positive_control/drag_scale_ukf_constructive_positive_control.json",
        "results/drag_scale_ukf_observability_positive_control/drag_scale_ukf_observability_positive_control.json",
        "release/predeclarations/drag_scale_constructive_positive_control_loop54.json",
        "release/predeclarations/drag_scale_ukf_constructive_positive_control_loop55.json",
        "release/predeclarations/drag_scale_ukf_observability_positive_control_loop56.json",
        "results/long_arc_hifi_force_mismatch/long_arc_hifi_force_mismatch_n64_loop57.json",
        "results/long_arc_hifi_force_mismatch/long_arc_hifi_force_mismatch.json",
        "release/predeclarations/long_arc_hifi_rule_loop47.json",
        "release/predeclarations/long_arc_hifi_n64_extension_loop57.json",
        "release/predeclarations/astrodynamics_floor_loop47.json",
        "results/observed_step_prospective_replication/observed_step_prospective_replication.json",
        "release/predeclarations/observed_step_prospective_replication_loop71.json",
        "results/observed_step_powered_stress_replication/observed_step_powered_stress_replication.json",
        "release/predeclarations/observed_step_powered_stress_replication.json",
        "results/observed_step_internal_prospective_replication_loop163_k96/observed_step_internal_prospective_replication_loop163_k96.json",
        "results/observed_step_internal_prospective_replication_loop163_k96/preregistration.json",
        "results/adaptation_risk_diagnostic/dbar_independent_sweep.json",
        "results/structural_channel_recoverability/structural_channel_recoverability.json",
        "release/predeclarations/structural_channel_recoverability_loop70.json",
        "results/validation/archive_extracted_reproduction.json",
        "results/validation/archive_extracted_real_slr_sp3_od_slice_rerun.json",
    ],
    "paper/tables/main_structural_recoverability.tex": [
        "results/structural_channel_recoverability/structural_channel_recoverability.json",
        "release/predeclarations/structural_channel_recoverability_loop70.json",
    ],
    "paper/tables/main_drag_scale_cascade.tex": [
        "results/drag_scale_constructive_positive_control/drag_scale_constructive_positive_control.json",
        "results/drag_scale_ukf_constructive_positive_control/drag_scale_ukf_constructive_positive_control.json",
        "results/drag_scale_ukf_observability_positive_control/drag_scale_ukf_observability_positive_control.json",
        "release/predeclarations/drag_scale_constructive_positive_control_loop54.json",
        "release/predeclarations/drag_scale_ukf_constructive_positive_control_loop55.json",
        "release/predeclarations/drag_scale_ukf_observability_positive_control_loop56.json",
    ],
    "paper/tables/main_k32_replication.tex": [
        "results/observed_step_prospective_replication/observed_step_prospective_replication.json",
        "release/predeclarations/observed_step_prospective_replication_loop71.json",
    ],
    "paper/tables/main_aukf_mechanism.tex": [
        "results/force_model_mismatch_adaptation_summary.json",
    ],
    "paper/tables/main_long_arc_result.tex": [
        "results/long_arc_hifi_force_mismatch/long_arc_hifi_force_mismatch_n64_loop57.json",
        "results/long_arc_hifi_force_mismatch/long_arc_hifi_force_mismatch.json",
        "release/predeclarations/long_arc_hifi_rule_loop47.json",
        "release/predeclarations/long_arc_hifi_n64_extension_loop57.json",
        "release/predeclarations/astrodynamics_floor_loop47.json",
    ],
    "paper/tables/main_dbar_withdrawal.tex": [
        "results/adaptation_risk_diagnostic/dbar_independent_sweep.json",
    ],
    "paper/tables/protocol_subset_ablation.tex": [
        "release/predeclarations/protocol_subset_ablation_loop51.json",
    ],
    "paper/tables/observed_step_prospective_replication.tex": [
        "results/observed_step_prospective_replication/observed_step_prospective_replication.json",
        "release/predeclarations/observed_step_prospective_replication_loop71.json",
    ],
    "paper/tables/seed_observed_significance.tex": [
        "results/seed_observed_significance_summary.csv",
        "results/seed_observed_significance.csv",
    ],
    "paper/tables/observed_step_preregistration.tex": [
        "results/observed_step_preregistration/observed_step_preregistration.json",
    ],
    "paper/tables/force_mismatch_mechanism.tex": [
        "results/force_model_mismatch_adaptation_summary.json",
    ],
    "paper/tables/hifi_force_mismatch.tex": [
        "results/hifi_force_mismatch/hifi_force_mismatch.json",
    ],
    "paper/tables/dmc_ekf_force_mismatch.tex": [
        "results/dmc_ekf_force_mismatch/dmc_ekf_force_mismatch.json",
        "release/predeclarations/dmc_ekf_rule_loop44.json",
        "release/predeclarations/pukf_q_adaptive_rule_loop41.json",
    ],
    "paper/tables/drag_scale_aekf_force_mismatch.tex": [
        "results/drag_scale_aekf_force_mismatch/drag_scale_aekf_force_mismatch.json",
        "release/predeclarations/drag_scale_aekf_rule_loop45.json",
    ],
    "paper/tables/long_arc_hifi_force_mismatch.tex": [
        "results/long_arc_hifi_force_mismatch/long_arc_hifi_force_mismatch_n64_loop57.json",
        "results/long_arc_hifi_force_mismatch/long_arc_hifi_force_mismatch.json",
        "release/predeclarations/long_arc_hifi_rule_loop47.json",
        "release/predeclarations/long_arc_hifi_n64_extension_loop57.json",
        "release/predeclarations/astrodynamics_floor_loop47.json",
    ],
}

TABLE_BUILDERS: dict[str, str] = {
    "paper/tables/main_abbreviation_glossary.tex": "build_main_abbreviation_glossary_table",
    "paper/tables/main_framework_portability.tex": "build_main_framework_portability_table",
    "paper/tables/main_findings_summary.tex": "build_main_findings_summary_table",
    "paper/tables/main_structural_recoverability.tex": "build_main_structural_recoverability_table",
    "paper/tables/main_drag_scale_cascade.tex": "build_main_drag_scale_cascade_table",
    "paper/tables/main_k32_replication.tex": "build_main_k32_replication_table",
    "paper/tables/main_aukf_mechanism.tex": "build_main_aukf_mechanism_table",
    "paper/tables/main_long_arc_result.tex": "build_main_long_arc_result_table",
    "paper/tables/main_dbar_withdrawal.tex": "build_main_dbar_withdrawal_table",
    "paper/tables/protocol_subset_ablation.tex": "build_protocol_subset_ablation_table",
    "paper/tables/observed_step_prospective_replication.tex": "build_observed_step_prospective_replication_table",
    "paper/tables/seed_observed_significance.tex": "build_seed_observed_significance_table",
    "paper/tables/observed_step_preregistration.tex": "build_observed_step_preregistration_table",
    "paper/tables/force_mismatch_mechanism.tex": "build_force_mismatch_mechanism_table",
    "paper/tables/hifi_force_mismatch.tex": "build_hifi_force_mismatch_table",
    "paper/tables/dmc_ekf_force_mismatch.tex": "build_dmc_ekf_force_mismatch_table",
    "paper/tables/drag_scale_aekf_force_mismatch.tex": "build_drag_scale_aekf_force_mismatch_table",
    "paper/tables/long_arc_hifi_force_mismatch.tex": "build_long_arc_hifi_force_mismatch_table",
}

FIGURE_SOURCES: dict[str, list[str]] = {
    "paper/figures/per_step_rmse.png": ["results/per_step_errors.csv"],
    "paper/figures/position_error_ecdf.png": ["results/trajectory_errors.csv"],
    "paper/figures/visibility_bucket_rmse.png": ["results/metrics_summary.json"],
    "paper/figures/uncertainty_calibration.png": ["results/uncertainty_calibration.csv"],
    "paper/figures/aukf_r_inflation_mechanism.png": [
        "results/force_model_mismatch_adaptation_summary.json",
        "results/force_model_mismatch_adaptation_updates.csv",
    ],
}


def rel(path: Path | str) -> str:
    p = Path(path)
    if not p.is_absolute():
        p = ROOT / p
    try:
        return str(p.relative_to(ROOT)).replace("/", "\\")
    except ValueError:
        return str(p).replace("/", "\\")


def posix_rel(path: Path | str) -> str:
    return rel(path).replace("\\", "/")


def repo_path(path: str | Path) -> Path:
    p = Path(str(path).replace("\\", os.sep).replace("/", os.sep))
    return p if p.is_absolute() else ROOT / p


def sha256(path: Path) -> str | None:
    if not path.exists() or not path.is_file():
        return None
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def artifact(path: Path | str) -> dict[str, Any]:
    p = repo_path(path)
    exists = p.exists() and p.is_file()
    return {
        "path": rel(p),
        "exists": exists,
        "bytes": p.stat().st_size if exists else None,
        "sha256": sha256(p) if exists else None,
    }


def strip_tex_comments(text: str) -> str:
    lines: list[str] = []
    for line in text.splitlines():
        escaped = False
        cut = len(line)
        for i, ch in enumerate(line):
            if ch == "\\":
                escaped = not escaped
                continue
            if ch == "%" and not escaped:
                cut = i
                break
            escaped = False
        lines.append(line[:cut])
    return "\n".join(lines)


def active_artifacts() -> dict[str, list[dict[str, Any]]]:
    tex = strip_tex_comments((PAPER / "main.tex").read_text(encoding="utf-8", errors="replace"))
    tables: list[dict[str, Any]] = []
    figures: list[dict[str, Any]] = []
    import re

    for i, line in enumerate(tex.splitlines(), 1):
        for m in re.finditer(r"\\input\{([^}]+)\}", line):
            target = m.group(1)
            p = PAPER / (target if target.endswith(".tex") else target + ".tex")
            if target.startswith("tables/"):
                tables.append({"line": i, "content": m.group(0), "path": rel(p)})
        for m in re.finditer(r"\\includegraphics(?:\[[^\]]*\])?\{([^}]+)\}", line):
            target = m.group(1)
            p = PAPER / target
            figures.append({"line": i, "content": m.group(0), "path": rel(p)})
    return {"tables": tables, "figures": figures}


def command_string() -> str:
    return "regenerate_active_manuscript_check"


def load_build_paper_assets() -> Any:
    scripts_dir = ROOT / "scripts"
    for item in (str(ROOT), str(scripts_dir)):
        if item not in sys.path:
            sys.path.insert(0, item)
    script = scripts_dir / "build_paper_assets.py"
    spec = importlib.util.spec_from_file_location("build_paper_assets", script)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot import {script}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)  # type: ignore[union-attr]
    return module


def write_tables(module: Any, out_dir: Path, active_table_paths: list[str]) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    records: list[dict[str, Any]] = []
    blockers: list[dict[str, Any]] = []
    for path in active_table_paths:
        posix = path.replace("\\", "/")
        builder_name = TABLE_BUILDERS.get(posix)
        if not builder_name:
            blockers.append(
                {
                    "path": path,
                    "stage": "table_generation",
                    "blocker": "No registered table builder for active manuscript table.",
                }
            )
            continue
        builder: Callable[[], str] | None = getattr(module, builder_name, None)
        if builder is None:
            blockers.append(
                {
                    "path": path,
                    "stage": "table_generation",
                    "blocker": f"Registered builder {builder_name} is missing.",
                }
            )
            continue
        try:
            content = builder()
            if content.lstrip().startswith("%") and "unavailable" in content.lower():
                blockers.append(
                    {
                        "path": path,
                        "stage": "table_generation",
                        "blocker": content.strip(),
                    }
                )
                continue
            dest = out_dir / posix
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(content, encoding="utf-8")
            records.append(
                {
                    "path": path,
                    "generated_temp": str(dest),
                    "sha256": sha256(dest),
                    "bytes": dest.stat().st_size,
                    "builder": f"scripts/build_paper_assets.py::{builder_name}",
                }
            )
        except Exception as exc:  # pragma: no cover - validation path
            blockers.append({"path": path, "stage": "table_generation", "blocker": repr(exc)})
    return records, blockers


def render_figures_to(out_dir: Path, active_figure_paths: list[str]) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    if not active_figure_paths:
        return [], []
    script = ROOT / "scripts" / "render_publication_figures.py"
    spec = importlib.util.spec_from_file_location("render_publication_figures", script)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot import {script}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)  # type: ignore[union-attr]
    fig_dir = out_dir / "paper" / "figures"
    report_path = out_dir / "results" / "publication_figure_render_report.json"
    try:
        report = module.render_publication_figures(results_dir=RESULTS, paper_fig_dir=fig_dir, report_path=report_path)
    except Exception as exc:
        return [], [{"path": path, "stage": "figure_generation", "blocker": repr(exc)} for path in active_figure_paths]
    by_name: dict[str, Path] = {}
    for info in report.get("figures", {}).values():
        p = Path(info["path"])
        by_name[p.name] = p
    records: list[dict[str, Any]] = []
    blockers: list[dict[str, Any]] = []
    for path in active_figure_paths:
        p = by_name.get(Path(path).name)
        if p is None:
            blockers.append({"path": path, "stage": "figure_generation", "blocker": "No rendered figure matched active includegraphics artifact."})
            continue
        records.append({"path": path, "generated_temp": str(p), "sha256": sha256(p), "bytes": p.stat().st_size, "builder": "scripts/render_publication_figures.py::render_publication_figures"})
    return records, blockers


def first_text_difference(current: str, generated: str) -> dict[str, Any] | None:
    current_lines = current.splitlines()
    generated_lines = generated.splitlines()
    max_len = max(len(current_lines), len(generated_lines))
    for idx in range(max_len):
        c = current_lines[idx] if idx < len(current_lines) else None
        g = generated_lines[idx] if idx < len(generated_lines) else None
        if c != g:
            return {"line": idx + 1, "current": c, "generated": g}
    if current != generated:
        return {
            "line": None,
            "current": "text differs only in trailing newline or byte-level encoding",
            "generated": "text differs only in trailing newline or byte-level encoding",
        }
    return None


def diff_summary(current_path: Path, generated_path: Path) -> dict[str, Any] | None:
    try:
        current = current_path.read_text(encoding="utf-8")
        generated = generated_path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return None
    diff = list(
        difflib.unified_diff(
            current.splitlines(),
            generated.splitlines(),
            fromfile=rel(current_path),
            tofile="regenerated/" + rel(current_path).replace("\\", "/"),
            lineterm="",
            n=2,
        )
    )
    return {
        "first_difference": first_text_difference(current, generated),
        "unified_diff_line_count": len(diff),
        "unified_diff_head": diff[:80],
        "current_trailing_newline": current.endswith("\n"),
        "generated_trailing_newline": generated.endswith("\n"),
    }


def compare_or_update_artifact(
    *,
    path: str,
    generated_temp: Path,
    source_evidence: list[dict[str, Any]],
    check_only: bool,
    command: str,
    builder: str | None,
) -> dict[str, Any]:
    target = repo_path(path)
    missing_sources = [src for src in source_evidence if not src["exists"]]
    before_hash = sha256(target)
    generated_hash = sha256(generated_temp)
    before_bytes = target.stat().st_size if target.exists() and target.is_file() else None
    if missing_sources:
        return {
            "path": path,
            "status": "blocked",
            "generation_step": command,
            "attempted": True,
            "exit_code": 1,
            "source_artifacts": source_evidence,
            "builder": builder,
            "explicit_blocker": "Missing source artifacts: " + ", ".join(m["path"] for m in missing_sources),
            "before_sha256": before_hash,
            "generated_sha256": generated_hash,
            "before_bytes": before_bytes,
            "generated_bytes": generated_temp.stat().st_size,
            "check_only": check_only,
        }
    preexisting_match = target.exists() and before_hash == generated_hash
    if not check_only:
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(generated_temp, target)
    after_hash = sha256(target)
    after_bytes = target.stat().st_size if target.exists() and target.is_file() else None
    status = "pass" if after_hash == generated_hash else "mismatch"
    record: dict[str, Any] = {
        "path": path,
        "status": status,
        "generation_step": command,
        "attempted": True,
        "exit_code": 0 if status == "pass" else 1,
        "source_artifacts": source_evidence,
        "builder": builder,
        "output_path": path,
        "before_sha256": before_hash,
        "generated_sha256": generated_hash,
        "after_sha256": after_hash,
        "before_bytes": before_bytes,
        "generated_bytes": generated_temp.stat().st_size,
        "bytes": after_bytes,
        "preexisting_match": preexisting_match,
        "check_only": check_only,
    }
    if not preexisting_match:
        record["difference"] = {
            "note": "Current artifact is missing; generated artifact was produced.",
            "current_exists": False,
            "generated_sha256": generated_hash,
        } if check_only else {
            "note": "Repository artifact was updated to regenerated bytes.",
            "before_sha256": before_hash,
            "generated_sha256": generated_hash,
        }
        if check_only and target.exists():
            record["difference"] = diff_summary(target, generated_temp)
    return record


def update_release_packet(status_evidence: dict[str, Any]) -> dict[str, Any]:
    if not RELEASE_PACKET.exists():
        return {"updated": False, "blocker": "results/release_packet.json missing"}
    packet = json.loads(RELEASE_PACKET.read_text(encoding="utf-8"))
    if not isinstance(packet.get("status_evidence"), dict):
        packet["status_evidence"] = {}
    packet["status_evidence"]["active_artifact_generation"] = status_evidence
    packet["active_artifact_generation_status"] = status_evidence
    packet["status_evidence"]["last_generation_harness_update_utc"] = status_evidence.get("generated_utc")
    RELEASE_PACKET.write_text(json.dumps(packet, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return {"updated": True, "path": rel(RELEASE_PACKET), "sha256": sha256(RELEASE_PACKET)}


def write_command_manifest(command: str, status_evidence: dict[str, Any], json_out: Path, md_out: Path, release_update: dict[str, Any]) -> None:
    manifest_path = VALIDATION / "command_manifest.json"
    manifest = {"commands": [], "status": "pass", "generated_utc": status_evidence["generated_utc"]}
    if manifest_path.exists():
        try:
            loaded = json.loads(manifest_path.read_text(encoding="utf-8"))
            if isinstance(loaded, dict):
                manifest = loaded
        except Exception:
            pass
    commands = [c for c in manifest.get("commands", []) if c.get("id") != "regenerate_active_manuscript"]
    for row in commands:
        row_id = row.get("id")
        if row_id == "compile_paper":
            row["evidence"] = [artifact("paper/main.pdf"), artifact("paper/main.log"), artifact("results/latexmk.log")]
        elif row_id == "verify_release_packet_sync":
            row["evidence"] = [artifact("results/validation/release_packet_sync.log"), artifact(RELEASE_PACKET)]
        elif row_id == "validate_submission":
            row["evidence"] = [
                artifact("results/validation/submission_validation_command.log"),
                artifact("results/validation/submission_validation.json"),
                artifact("results/validation/submission_validation.md"),
            ]
        elif row_id == "task227_final_validation":
            row["evidence"] = [
                artifact("results/task227_final_submission_validation_result_payload.json"),
                artifact("results/validation/task227_final_validation.json"),
            ]
        elif row_id == "pytest":
            row["evidence"] = [artifact("results/validation/pytest.log")]
    passed = status_evidence["status"] == "pass"
    commands.insert(
        0,
        {
            "id": "regenerate_active_manuscript",
            "step": command,
            "execution_details_redacted": True,
            "status": "pass" if passed else "fail",
            "exit_code": 0 if passed else 1,
            "scope_boundary": SCOPE_BOUNDARY,
            "evidence": [artifact(json_out), artifact(md_out), artifact(RELEASE_PACKET)],
            "artifact_generation_status": status_evidence["active_artifacts"],
            "python_isolated_mode": bool(sys.flags.isolated),
            "release_packet_update": release_update,
        },
    )
    manifest["commands"] = commands
    manifest["generated_utc"] = status_evidence["generated_utc"]
    manifest["status"] = "pass" if all(c.get("status") == "pass" for c in commands) else "fail"
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Regenerate active main-manuscript artifacts from materialized result artifacts.")
    parser.add_argument("--check-only", action="store_true", help="Generate in a temporary directory and compare without replacing paper artifacts.")
    parser.add_argument("--json-out", default="results/validation/active_manuscript_regeneration.json")
    parser.add_argument("--md-out", default="results/validation/active_manuscript_regeneration.md")
    args = parser.parse_args()

    generated_utc = dt.datetime.now(dt.timezone.utc).isoformat()
    command = command_string()
    active = active_artifacts()
    active_table_paths = [row["path"] for row in active["tables"]]
    active_figure_paths = [row["path"] for row in active["figures"]]
    expected_paths = active_table_paths + active_figure_paths

    records_by_path: dict[str, dict[str, Any]] = {}
    blockers: list[dict[str, Any]] = []
    with tempfile.TemporaryDirectory(prefix="active_manuscript_regen_") as td:
        temp_root = Path(td)
        try:
            module = load_build_paper_assets()
            table_records, table_blockers = write_tables(module, temp_root, active_table_paths)
            blockers.extend(table_blockers)
            for row in table_records:
                records_by_path[row["path"]] = row
        except Exception as exc:
            blockers.extend({"path": path, "stage": "table_generation", "blocker": repr(exc)} for path in active_table_paths)

        figure_records, figure_blockers = render_figures_to(temp_root, active_figure_paths)
        blockers.extend(figure_blockers)
        for row in figure_records:
            records_by_path[row["path"]] = row

        artifact_records: list[dict[str, Any]] = []
        for path in expected_paths:
            rec = records_by_path.get(path)
            source_paths = ACTIVE_TABLE_SOURCES.get(path.replace("\\", "/"), FIGURE_SOURCES.get(path.replace("\\", "/"), []))
            source_evidence = [artifact(src) for src in source_paths]
            if rec is None:
                explicit = next((b for b in blockers if b["path"] == path), None)
                artifact_records.append(
                    {
                        "path": path,
                        "status": "blocked",
                        "generation_step": command,
                        "attempted": True,
                        "exit_code": 1,
                        "source_artifacts": source_evidence,
                        "blocker": explicit["blocker"] if explicit else "No generator record produced for active artifact.",
                        "stage": explicit.get("stage") if explicit else None,
                        "check_only": bool(args.check_only),
                    }
                )
                continue
            artifact_records.append(
                compare_or_update_artifact(
                    path=path,
                    generated_temp=Path(rec["generated_temp"]),
                    source_evidence=source_evidence,
                    check_only=bool(args.check_only),
                    command=command,
                    builder=rec.get("builder"),
                )
            )

    documented_blocker_count = sum(1 for row in artifact_records if row.get("status") == "blocked")
    mismatch_count = sum(1 for row in artifact_records if row.get("status") == "mismatch")
    pass_count = sum(1 for row in artifact_records if row.get("status") == "pass")
    regeneration_complete = len(artifact_records) == len(expected_paths) and documented_blocker_count == 0 and mismatch_count == 0
    status_evidence = {
        "status": "pass" if regeneration_complete else "failed",
        "regeneration_complete": regeneration_complete,
        "documented_blocker_count": documented_blocker_count,
        "mismatch_count": mismatch_count,
        "pass_count": pass_count,
        "generated_utc": generated_utc,
        "one_step_harness": "regenerate_active_manuscript_check",
        "executed_step": command,
        "scope_boundary": SCOPE_BOUNDARY,
        "fresh_run_approximation": {
            "temporary_output_directory": True,
            "python_isolated_mode": bool(sys.flags.isolated),
            "uses_current_repository_source": True,
            "uses_current_interpreter": True,
            "independent_reproduction_claimed": False,
        },
        "active_artifact_count": len(artifact_records),
        "active_artifacts": artifact_records,
        "active_tables_from_main_tex": active["tables"],
        "active_figures_from_main_tex": active["figures"],
    }
    release_update = update_release_packet(status_evidence)

    result = {
        "status": status_evidence["status"],
        "tests_passed": regeneration_complete,
        "validation_results": {
            "active_artifact_regeneration_complete": regeneration_complete,
            "artifact_count": len(artifact_records),
            "documented_blocker_count": documented_blocker_count,
            "mismatch_count": mismatch_count,
            "pass_count": pass_count,
        },
        "generated_utc": generated_utc,
        "step": command,
        "changed_files": [
            "scripts/regenerate_active_manuscript.py",
            "scripts/build_paper_assets.py",
            "results/release_packet.json",
            "results/validation/active_manuscript_regeneration.json",
            "results/validation/active_manuscript_regeneration.md",
            "results/validation/command_manifest.json",
        ],
        "status_evidence": status_evidence,
        "release_packet_update": release_update,
        "claim_boundary": SCOPE_BOUNDARY,
    }

    json_out = repo_path(args.json_out)
    md_out = repo_path(args.md_out)
    json_out.parent.mkdir(parents=True, exist_ok=True)
    md_out.parent.mkdir(parents=True, exist_ok=True)
    json_out.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    md_lines = [
        "# Active Main-Manuscript Regeneration Harness Report",
        "",
        f"Generated UTC: `{generated_utc}`",
        f"Step: `{command}`",
        f"Status: **{result['status'].upper()}**",
        "",
        "## Scope boundary",
        SCOPE_BOUNDARY,
        "",
        "## Fresh-run approximation",
        "- Generated artifacts were written to a temporary output directory before comparison.",
        f"- Python isolated mode: `{bool(sys.flags.isolated)}`.",
        "- This is not an independent reproduction; it uses the current repository source and current Python interpreter.",
        "",
        "## Artifact-level generation status",
        "| Artifact | Status | Current SHA-256 | Regenerated SHA-256 | Source artifacts | Difference/blocker |",
        "|---|---:|---|---|---|---|",
    ]
    for row in artifact_records:
        src = "; ".join(s["path"] for s in row.get("source_artifacts", [])) or "None recorded"
        diff = row.get("blocker") or row.get("explicit_blocker") or ""
        if not diff and row.get("difference"):
            first = row["difference"].get("first_difference") if isinstance(row["difference"], dict) else None
            if first:
                diff = f"line {first.get('line')}: current={first.get('current')!r}; generated={first.get('generated')!r}"
            else:
                diff = row["difference"].get("note", "byte mismatch") if isinstance(row["difference"], dict) else "byte mismatch"
        md_lines.append(
            f"| `{row['path']}` | `{row['status']}` | `{row.get('before_sha256') or row.get('after_sha256')}` | "
            f"`{row.get('generated_sha256')}` | {src} | {diff or 'None'} |"
        )
    md_lines += [
        "",
        "## Verification notes",
        f"- Active artifacts parsed from `paper/main.tex`: {len(active['tables'])} tables and {len(active['figures'])} external figure includes.",
        f"- Pass count: `{pass_count}`; mismatch count: `{mismatch_count}`; blocker count: `{documented_blocker_count}`.",
        f"- Release packet update: `{release_update}`.",
        "- The harness does not rerun raw-data simulation, training, filter estimation, or live public-data fetches.",
    ]
    md_out.write_text("\n".join(md_lines) + "\n", encoding="utf-8")

    write_command_manifest(command, status_evidence, json_out, md_out, release_update)
    print(
        json.dumps(
            {
                "status": result["status"],
                "json": rel(json_out),
                "markdown": rel(md_out),
                "release_packet": rel(RELEASE_PACKET),
                "artifact_count": len(artifact_records),
                "pass_count": pass_count,
                "mismatch_count": mismatch_count,
                "blocker_count": documented_blocker_count,
                "python_isolated_mode": bool(sys.flags.isolated),
            },
            indent=2,
        )
    )
    return 0 if regeneration_complete else 1


if __name__ == "__main__":
    raise SystemExit(main())
