#!/usr/bin/env python
"""Higher-fidelity force-mismatch experiment (Loop 42, M3).

A reviewer concern on Loop 41 was that the compact two-body+J2 force model
ceiling makes the AUKF-under-dynamics-bias mechanism diagnostic only a
*compact-model* prescription: the controlled mismatch on
``force_model_mismatch_test`` inflates parameters of the SAME compact model
(ballistic coefficient, drag density, SRP). This script raises the truth-side
fidelity *above* that ceiling so the mismatch is a missing-physics gap, not
an inflated-parameter gap. The truth-side dynamics include the
J2+J3+J4 zonal geopotential and luni-solar third-body acceleration (the
``accel_hifi`` higher-fidelity propagator already verified against analytic
gradients in tests/test_sp3_hifi_smoke.py). The recursive filters and PUKF
keep the *nominal compact* two-body+J2+drag model, exactly as in the rest of
the manuscript, so this is a deliberate, harder force-model mismatch the
estimator cannot solve from inside its own model class.

The script reuses the same observed-step convention, the same paired
trajectory-bootstrap protocol, and the same EKF/UKF/AUKF/PUKF tuning as the
Loop 41 mechanism diagnostic so the second-fidelity result is directly
comparable to Table 8.

Outputs:
- results/hifi_force_mismatch/hifi_force_mismatch.json (full payload)
- results/hifi_force_mismatch/hifi_force_mismatch.csv (per-trajectory)

This script is non-paper-facing. The paper-facing table is generated by
``scripts/build_paper_assets.py`` from the JSON.
"""
from __future__ import annotations

try:
    from _bootstrap import ensure_src_on_path
except ModuleNotFoundError:  # pragma: no cover
    from scripts._bootstrap import ensure_src_on_path

ensure_src_on_path()

import argparse
import hashlib
import json
import time
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from scipy.stats import wilcoxon

from gnn_state_estimation.constants import EARTH_ROTATION_RATE
from gnn_state_estimation.coordinates import (
    StationGeometry,
    line_of_sight_measurement,
    station_to_ecef,
)
from gnn_state_estimation.dynamics import (
    atmospheric_density_exponential,
    kepler_to_cartesian,
)
from gnn_state_estimation.evaluation import parse_baseline_config
from gnn_state_estimation.filters import (
    EKFConfig,
    UKFConfig,
    AdaptiveUKFConfig,
    ProcessNoiseAdaptiveUKFConfig,
    run_ekf,
    run_ukf,
    run_adaptive_ukf,
    run_process_noise_adaptive_ukf,
)
from gnn_state_estimation.simulation import OrbitSamplingConfig, parse_dataset_config
from gnn_state_estimation.sp3 import accel_hifi
from gnn_state_estimation.utils.io import load_yaml


# --- Truth-side higher-fidelity propagator ---------------------------------


def _hifi_drag_acceleration(
    r_eci: np.ndarray,
    v_eci: np.ndarray,
    ballistic_coeff_m2_per_kg: float,
    drag_rho_ref: float,
    drag_h_ref_m: float,
    drag_scale_height_m: float,
) -> np.ndarray:
    """Exponential-atmosphere drag with co-rotating wind (same model used
    by the compact estimator); kept so the truth/estimator mismatch is
    *exclusively* in the conservative force field, not in atmosphere."""
    r = float(np.linalg.norm(r_eci))
    if r < 1.0:
        return np.zeros(3, dtype=np.float64)
    altitude = r - 6378.1363e3
    rho = atmospheric_density_exponential(
        altitude_m=altitude,
        rho_ref=drag_rho_ref,
        h_ref_m=drag_h_ref_m,
        scale_height_m=drag_scale_height_m,
    )
    omega = np.array([0.0, 0.0, EARTH_ROTATION_RATE], dtype=np.float64)
    v_atm = np.cross(omega, r_eci)
    v_rel = v_eci - v_atm
    v_rel_norm = float(np.linalg.norm(v_rel))
    return -0.5 * ballistic_coeff_m2_per_kg * rho * v_rel_norm * v_rel


def _hifi_state_derivative(
    state: np.ndarray,
    epoch_unix: float,
    ballistic_coeff_m2_per_kg: float,
    drag_rho_ref: float,
    drag_h_ref_m: float,
    drag_scale_height_m: float,
) -> np.ndarray:
    r = state[:3]
    v = state[3:]
    a = accel_hifi(r, epoch_unix)  # two-body + J2..J4 + luni-solar third body
    a = a + _hifi_drag_acceleration(
        r,
        v,
        ballistic_coeff_m2_per_kg=ballistic_coeff_m2_per_kg,
        drag_rho_ref=drag_rho_ref,
        drag_h_ref_m=drag_h_ref_m,
        drag_scale_height_m=drag_scale_height_m,
    )
    return np.hstack([v, a]).astype(np.float64)


def _hifi_rk4_step(
    state: np.ndarray,
    dt: float,
    epoch_unix: float,
    ballistic_coeff_m2_per_kg: float,
    drag_rho_ref: float,
    drag_h_ref_m: float,
    drag_scale_height_m: float,
) -> np.ndarray:
    kwargs = dict(
        ballistic_coeff_m2_per_kg=ballistic_coeff_m2_per_kg,
        drag_rho_ref=drag_rho_ref,
        drag_h_ref_m=drag_h_ref_m,
        drag_scale_height_m=drag_scale_height_m,
    )
    k1 = _hifi_state_derivative(state, epoch_unix, **kwargs)
    k2 = _hifi_state_derivative(state + 0.5 * dt * k1, epoch_unix + 0.5 * dt, **kwargs)
    k3 = _hifi_state_derivative(state + 0.5 * dt * k2, epoch_unix + 0.5 * dt, **kwargs)
    k4 = _hifi_state_derivative(state + dt * k3, epoch_unix + dt, **kwargs)
    return (state + (dt / 6.0) * (k1 + 2.0 * k2 + 2.0 * k3 + k4)).astype(np.float64)


def _propagate_hifi_trajectory(
    x0: np.ndarray,
    dt: float,
    steps: int,
    epoch0_unix: float,
    ballistic_coeff_m2_per_kg: float,
    drag_rho_ref: float,
    drag_h_ref_m: float,
    drag_scale_height_m: float,
) -> np.ndarray:
    states = np.zeros((steps, 6), dtype=np.float64)
    states[0] = np.asarray(x0, dtype=np.float64)
    for k in range(1, steps):
        states[k] = _hifi_rk4_step(
            states[k - 1],
            dt=dt,
            epoch_unix=epoch0_unix + (k - 1) * dt,
            ballistic_coeff_m2_per_kg=ballistic_coeff_m2_per_kg,
            drag_rho_ref=drag_rho_ref,
            drag_h_ref_m=drag_h_ref_m,
            drag_scale_height_m=drag_scale_height_m,
        )
    return states


def _sample_orbit(
    orbit_cfg: OrbitSamplingConfig, rng: np.random.Generator
) -> np.ndarray:
    earth_radius_m = 6378.1363e3
    altitude_m = rng.uniform(orbit_cfg.altitude_min_km, orbit_cfg.altitude_max_km) * 1e3
    semi_major_axis_m = earth_radius_m + altitude_m
    eccentricity = rng.uniform(orbit_cfg.eccentricity_min, orbit_cfg.eccentricity_max)
    inclination_rad = np.deg2rad(
        rng.uniform(orbit_cfg.inclination_min_deg, orbit_cfg.inclination_max_deg)
    )
    raan_rad = rng.uniform(0.0, 2.0 * np.pi)
    arg_perigee_rad = rng.uniform(0.0, 2.0 * np.pi)
    true_anomaly_rad = rng.uniform(0.0, 2.0 * np.pi)
    return kepler_to_cartesian(
        semi_major_axis_m=semi_major_axis_m,
        eccentricity=eccentricity,
        inclination_rad=inclination_rad,
        raan_rad=raan_rad,
        arg_perigee_rad=arg_perigee_rad,
        true_anomaly_rad=true_anomaly_rad,
    )


def _wrap_azimuth(az: float) -> float:
    if az < 0.0:
        az += 2.0 * np.pi
    if az >= 2.0 * np.pi:
        az -= 2.0 * np.pi
    return az


def _generate_observations(
    states: np.ndarray,
    times: np.ndarray,
    stations: tuple[StationGeometry, ...],
    noise_std: np.ndarray,
    outlier_prob: float,
    outlier_scale: float,
    dropout_prob: float,
    rng: np.random.Generator,
) -> tuple[np.ndarray, np.ndarray]:
    steps = states.shape[0]
    n_stations = len(stations)
    meas = np.zeros((steps, n_stations, 4), dtype=np.float64)
    vis = np.zeros((steps, n_stations), dtype=np.float64)
    for t_idx, t_s in enumerate(times):
        for s_idx, station in enumerate(stations):
            z_true, visible = line_of_sight_measurement(states[t_idx], station, float(t_s))
            if not visible:
                continue
            if rng.uniform() < dropout_prob:
                continue
            eps = rng.normal(0.0, noise_std)
            if rng.uniform() < outlier_prob:
                eps *= outlier_scale
            z_noisy = z_true + eps
            z_noisy[1] = _wrap_azimuth(float(z_noisy[1]))
            z_noisy[2] = float(np.clip(z_noisy[2], -0.5 * np.pi, 0.5 * np.pi))
            meas[t_idx, s_idx] = z_noisy
            vis[t_idx, s_idx] = 1.0
    return meas, vis


# --- Observed-step / paired-bootstrap (same convention as Table 8) ---------


def _per_traj_observed_pos_rmse(
    states: np.ndarray, preds: np.ndarray, visibility: np.ndarray, eval_start: int
) -> np.ndarray:
    eval_vis = visibility[:, eval_start:]
    observed = np.sum(eval_vis, axis=-1) >= 0.5
    y_true = states[:, eval_start:, :3]
    y_pred = preds[:, eval_start:, :3]
    out = np.full(states.shape[0], np.nan, dtype=np.float64)
    for i in range(states.shape[0]):
        mask = observed[i]
        if not np.any(mask):
            continue
        err = y_true[i, mask] - y_pred[i, mask]
        out[i] = float(np.sqrt(np.mean(np.sum(err * err, axis=-1))))
    return out


def _paired_bootstrap_ci(
    diffs: np.ndarray, n_boot: int, seed: int, alpha: float = 0.05
) -> tuple[float, float, float]:
    finite = diffs[np.isfinite(diffs)]
    if finite.size == 0:
        return float("nan"), float("nan"), float("nan")
    rng = np.random.default_rng(seed)
    means = np.empty(n_boot, dtype=np.float64)
    n = finite.size
    for b in range(n_boot):
        idx = rng.integers(0, n, n)
        means[b] = float(np.mean(finite[idx]))
    return (
        float(np.mean(finite)),
        float(np.quantile(means, alpha / 2)),
        float(np.quantile(means, 1.0 - alpha / 2)),
    )


def _one_sided_wilcoxon_candidate_better(diffs: np.ndarray) -> float:
    """One-sided paired signed-rank: alternative = candidate < baseline.

    ``diffs`` is candidate - baseline, so negative favours the candidate.
    Returns the one-sided ``alternative='less'`` p-value as a descriptive
    diagnostic.
    """
    finite = diffs[np.isfinite(diffs)]
    if finite.size == 0 or np.allclose(finite, 0.0):
        return float("nan")
    try:
        return float(wilcoxon(finite, alternative="less", zero_method="wilcox").pvalue)
    except Exception:
        return float("nan")


# --- AUKF cross-filter R-only NIS diagnostic --------------------------------


def _cross_filter_r_only_nis(
    states: np.ndarray,
    preds: np.ndarray,
    measurements: np.ndarray,
    visibility: np.ndarray,
    times: np.ndarray,
    stations: tuple[StationGeometry, ...],
    meas_std: np.ndarray,
    eval_start: int,
) -> dict[str, float]:
    """Median NIS computed against fixed nominal R only (no adaptive scale).

    NIS = innovation^T R^{-1} innovation, where the innovation is the residual
    between the actual measurement and the predicted measurement at the
    filter's posterior state. We use the FIXED nominal R for every filter, so
    differences across filters reflect how each filter's posterior tracks the
    measurement at the same effective measurement-noise weighting -- exactly
    the cross-filter diagnostic of Table 8.
    """
    r_diag = (np.asarray(meas_std, dtype=np.float64) ** 2)
    nis_vals: list[float] = []
    n_traj = states.shape[0]
    for i in range(n_traj):
        for k in range(eval_start, states.shape[1]):
            for s_idx, station in enumerate(stations):
                if visibility[i, k, s_idx] < 0.5:
                    continue
                z_obs = measurements[i, k, s_idx]
                z_pred, _ = line_of_sight_measurement(preds[i, k], station, float(times[i, k]))
                y = z_obs - z_pred
                # Wrap azimuth residual to (-pi, pi]
                y1 = float(y[1])
                y1 = (y1 + np.pi) % (2.0 * np.pi) - np.pi
                y_eff = np.array([float(y[0]), y1, float(y[2]), float(y[3])])
                nis_vals.append(float(np.sum((y_eff * y_eff) / r_diag)))
    if not nis_vals:
        return {"median": float("nan"), "n": 0}
    arr = np.asarray(nis_vals, dtype=np.float64)
    return {
        "median": float(np.median(arr)),
        "mean": float(np.mean(arr)),
        "p90": float(np.percentile(arr, 90.0)),
        "n": int(arr.size),
    }


# --- Main -------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--config", default="configs/experiment.yaml")
    p.add_argument(
        "--predeclared-rule",
        default="release/predeclarations/pukf_q_adaptive_rule_loop41.json",
    )
    p.add_argument("--output-json", default="results/hifi_force_mismatch/hifi_force_mismatch.json")
    p.add_argument("--output-csv", default="results/hifi_force_mismatch/hifi_force_mismatch.csv")
    p.add_argument("--trajectories", type=int, default=48)
    p.add_argument("--seed", type=int, default=20260520)
    p.add_argument(
        "--epoch-unix",
        type=float,
        default=1_736_640_000.0,
        help="Absolute UTC epoch for the luni-solar ephemerides (default 2025-01-12 ~).",
    )
    p.add_argument("--bootstrap-samples", type=int, default=5000)
    return p


def main() -> int:
    args = build_parser().parse_args()
    cfg = load_yaml(Path(args.config))
    nominal_sim = cfg["simulation"]
    dataset_cfg = parse_dataset_config(nominal_sim)
    dyn = dataset_cfg.dynamics
    stations = dataset_cfg.stations
    meas_std = dataset_cfg.measurement_noise.std_vector

    baseline_cfg = parse_baseline_config(cfg["baselines"])
    rule = json.loads(Path(args.predeclared_rule).read_text())
    th = rule["thresholds"]

    eval_start = 11  # window-size-1, same as the rest of the manuscript

    rng = np.random.default_rng(args.seed)
    n_traj = int(args.trajectories)
    steps = dyn.steps
    dt = dyn.dt_s
    times = np.tile(np.arange(steps, dtype=np.float64) * dt, (n_traj, 1))

    # Estimator-side compact-model drag/atmosphere parameters (NOT used by
    # the truth, which uses J2..J4 + luni-solar + same drag).
    truth_ballistic = dyn.ballistic_coeff_m2_per_kg
    truth_rho_ref = dyn.drag_rho_ref
    truth_h_ref = dyn.drag_h_ref_m
    truth_scale_h = dyn.drag_scale_height_m

    states_all = np.zeros((n_traj, steps, 6), dtype=np.float64)
    meas_all = np.zeros((n_traj, steps, len(stations), 4), dtype=np.float64)
    vis_all = np.zeros((n_traj, steps, len(stations)), dtype=np.float64)
    x0_est_all = np.zeros((n_traj, 6), dtype=np.float64)

    init_pos_sigma = baseline_cfg.ukf.init_pos_std_m
    init_vel_sigma = baseline_cfg.ukf.init_vel_std_mps

    t_gen = time.perf_counter()
    for i in range(n_traj):
        x0 = _sample_orbit(dataset_cfg.orbit_sampling, rng)
        states = _propagate_hifi_trajectory(
            x0,
            dt=dt,
            steps=steps,
            epoch0_unix=args.epoch_unix,
            ballistic_coeff_m2_per_kg=truth_ballistic,
            drag_rho_ref=truth_rho_ref,
            drag_h_ref_m=truth_h_ref,
            drag_scale_height_m=truth_scale_h,
        )
        meas, vis = _generate_observations(
            states=states,
            times=times[i],
            stations=stations,
            noise_std=meas_std,
            outlier_prob=dataset_cfg.measurement_noise.outlier_prob,
            outlier_scale=dataset_cfg.measurement_noise.outlier_scale,
            dropout_prob=dataset_cfg.measurement_noise.random_dropout_prob,
            rng=rng,
        )
        x0_perturb = np.array(
            [
                rng.normal(0.0, init_pos_sigma),
                rng.normal(0.0, init_pos_sigma),
                rng.normal(0.0, init_pos_sigma),
                rng.normal(0.0, init_vel_sigma),
                rng.normal(0.0, init_vel_sigma),
                rng.normal(0.0, init_vel_sigma),
            ]
        )
        states_all[i] = states
        meas_all[i] = meas
        vis_all[i] = vis
        x0_est_all[i] = states[0] + x0_perturb
    t_gen = time.perf_counter() - t_gen

    # Estimator (compact two-body+J2+drag) - SHARED across EKF/UKF/AUKF/PUKF.
    ekf_kwargs = dict(
        ballistic_coeff_m2_per_kg=dyn.ballistic_coeff_m2_per_kg,
        drag_rho_ref=dyn.drag_rho_ref,
        drag_h_ref_m=dyn.drag_h_ref_m,
        drag_scale_height_m=dyn.drag_scale_height_m,
        enable_third_body=dyn.enable_third_body,
        enable_srp=dyn.enable_srp,
        srp_area_to_mass_m2_per_kg=dyn.srp_area_to_mass_m2_per_kg,
        srp_cr=dyn.srp_cr,
        sun_initial_phase_rad=dyn.sun_initial_phase_rad,
        moon_initial_phase_rad=dyn.moon_initial_phase_rad,
    )
    ekf_cfg = EKFConfig(
        q_pos_m=baseline_cfg.ekf.q_pos_m,
        q_vel_mps=baseline_cfg.ekf.q_vel_mps,
        init_pos_std_m=baseline_cfg.ekf.init_pos_std_m,
        init_vel_std_mps=baseline_cfg.ekf.init_vel_std_mps,
        gating_threshold=baseline_cfg.ekf.gating_threshold,
        angle_deweight_elev_cap_deg=getattr(
            baseline_cfg.ekf, "angle_deweight_elev_cap_deg", None
        ),
    )
    ukf_cfg = UKFConfig(
        q_pos_m=baseline_cfg.ukf.q_pos_m,
        q_vel_mps=baseline_cfg.ukf.q_vel_mps,
        init_pos_std_m=baseline_cfg.ukf.init_pos_std_m,
        init_vel_std_mps=baseline_cfg.ukf.init_vel_std_mps,
        alpha=baseline_cfg.ukf.alpha,
        beta=baseline_cfg.ukf.beta,
        kappa=baseline_cfg.ukf.kappa,
        angle_deweight_elev_cap_deg=getattr(
            baseline_cfg.ukf, "angle_deweight_elev_cap_deg", None
        ),
    )
    aukf_cfg_kwargs = dict(
        q_pos_m=baseline_cfg.aukf.q_pos_m,
        q_vel_mps=baseline_cfg.aukf.q_vel_mps,
        init_pos_std_m=baseline_cfg.aukf.init_pos_std_m,
        init_vel_std_mps=baseline_cfg.aukf.init_vel_std_mps,
        alpha=baseline_cfg.aukf.alpha,
        beta=baseline_cfg.aukf.beta,
        kappa=baseline_cfg.aukf.kappa,
        adapt_rate=baseline_cfg.aukf.adapt_rate,
        min_r_scale=baseline_cfg.aukf.min_r_scale,
        max_r_scale=baseline_cfg.aukf.max_r_scale,
        huber_kappa=baseline_cfg.aukf.huber_kappa,
        nis_soft_gate=baseline_cfg.aukf.nis_soft_gate,
        angle_deweight_elev_cap_deg=getattr(
            baseline_cfg.aukf, "angle_deweight_elev_cap_deg", None
        ),
    )
    aukf_cfg = AdaptiveUKFConfig(**aukf_cfg_kwargs)
    pukf_cfg = ProcessNoiseAdaptiveUKFConfig(
        q_pos_m=baseline_cfg.ukf.q_pos_m,
        q_vel_mps=baseline_cfg.ukf.q_vel_mps,
        init_pos_std_m=baseline_cfg.ukf.init_pos_std_m,
        init_vel_std_mps=baseline_cfg.ukf.init_vel_std_mps,
        alpha=baseline_cfg.ukf.alpha,
        beta=baseline_cfg.ukf.beta,
        kappa=baseline_cfg.ukf.kappa,
        window_size=int(th["window_size"]),
        nis_per_update_expected=float(th["nis_per_update_expected"]),
        nis_warn_ratio=float(th["nis_warn_ratio"]),
        nis_alarm_ratio=float(th["nis_alarm_ratio"]),
        q_scale_warn=float(th["q_scale_warn"]),
        q_scale_alarm=float(th["q_scale_alarm"]),
        q_scale_max=float(th["q_scale_max"]),
        smoothing=float(th["smoothing"]),
        angle_deweight_elev_cap_deg=getattr(
            baseline_cfg.ukf, "angle_deweight_elev_cap_deg", None
        ),
    )

    ekf_pred = np.zeros_like(states_all)
    ukf_pred = np.zeros_like(states_all)
    aukf_pred = np.zeros_like(states_all)
    pukf_pred = np.zeros_like(states_all)
    pukf_q_scales: list[float] = []

    t_filt = time.perf_counter()
    for i in range(n_traj):
        ekf_pred[i], _ = run_ekf(
            measurements=meas_all[i],
            visibility=vis_all[i],
            times_s=times[i],
            stations=stations,
            meas_std_vector=meas_std,
            x0_est=x0_est_all[i],
            cfg=ekf_cfg,
            **ekf_kwargs,
        )
        ukf_pred[i], _ = run_ukf(
            measurements=meas_all[i],
            visibility=vis_all[i],
            times_s=times[i],
            stations=stations,
            meas_std_vector=meas_std,
            x0_est=x0_est_all[i],
            cfg=ukf_cfg,
            **ekf_kwargs,
        )
        aukf_pred[i], _ = run_adaptive_ukf(
            measurements=meas_all[i],
            visibility=vis_all[i],
            times_s=times[i],
            stations=stations,
            meas_std_vector=meas_std,
            x0_est=x0_est_all[i],
            cfg=aukf_cfg,
            **ekf_kwargs,
        )
        pukf_pred[i], _, pukf_recs = run_process_noise_adaptive_ukf(
            measurements=meas_all[i],
            visibility=vis_all[i],
            times_s=times[i],
            stations=stations,
            meas_std_vector=meas_std,
            x0_est=x0_est_all[i],
            cfg=pukf_cfg,
            **ekf_kwargs,
        )
        for rec in pukf_recs:
            pukf_q_scales.append(float(rec["q_scale_used"]))
    t_filt = time.perf_counter() - t_filt

    # Per-trajectory observed-step RMSE.
    metrics = {
        "EKF": _per_traj_observed_pos_rmse(states_all, ekf_pred, vis_all, eval_start),
        "UKF": _per_traj_observed_pos_rmse(states_all, ukf_pred, vis_all, eval_start),
        "AUKF": _per_traj_observed_pos_rmse(states_all, aukf_pred, vis_all, eval_start),
        "PUKF": _per_traj_observed_pos_rmse(states_all, pukf_pred, vis_all, eval_start),
    }
    means = {k: float(np.nanmean(v)) for k, v in metrics.items()}

    # Paired bootstraps for the same comparison set as Table 8.
    paired: dict[str, dict[str, float]] = {}
    pair_specs = [
        ("EKF", "AUKF"),  # candidate, baseline -- EKF better => diff<0
        ("EKF", "UKF"),
        ("UKF", "AUKF"),
        ("PUKF", "EKF"),
        ("PUKF", "UKF"),
        ("PUKF", "AUKF"),
    ]
    rng_offset = 0
    for cand, base in pair_specs:
        diffs = metrics[cand] - metrics[base]  # negative => candidate better
        mean, lo, hi = _paired_bootstrap_ci(
            diffs, n_boot=int(args.bootstrap_samples), seed=args.seed + rng_offset
        )
        rng_offset += 1
        p = _one_sided_wilcoxon_candidate_better(diffs)
        finite = diffs[np.isfinite(diffs)]
        paired[f"{cand}_minus_{base}"] = {
            "candidate": cand,
            "baseline": base,
            "mean_diff_m": mean,
            "ci_lo_m": lo,
            "ci_hi_m": hi,
            "wilcoxon_p_one_sided_candidate_better": p,
            "n_paired": int(finite.size),
            "candidate_better_count": int(np.sum(finite < 0.0)),
        }

    # AUKF cross-filter R-only NIS diagnostic (the Table 8 diagnostic).
    nis_per_filter = {}
    for name, preds in (
        ("EKF", ekf_pred),
        ("UKF", ukf_pred),
        ("AUKF", aukf_pred),
        ("PUKF", pukf_pred),
    ):
        nis_per_filter[name] = _cross_filter_r_only_nis(
            states_all,
            preds,
            meas_all,
            vis_all,
            times,
            stations,
            meas_std,
            eval_start,
        )

    payload: dict[str, Any] = {
        "scenario": "hifi_force_mismatch",
        "scope": (
            "Higher-fidelity force-model mismatch: truth uses two-body + J2/J3/J4 "
            "zonal geopotential + luni-solar third-body acceleration + the same "
            "exponential-atmosphere drag; estimators use the nominal compact "
            "two-body+J2+drag model. The missing-physics gap is conservative, "
            "not parameter-inflated."
        ),
        "n_trajectories": int(n_traj),
        "steps": int(steps),
        "dt_s": float(dt),
        "eval_start_step": int(eval_start),
        "epoch_unix": float(args.epoch_unix),
        "rng_seed": int(args.seed),
        "bootstrap_samples": int(args.bootstrap_samples),
        "predeclared_rule_path": args.predeclared_rule,
        "predeclared_rule_digest_sha256": hashlib.sha256(
            Path(args.predeclared_rule).read_bytes()
        ).hexdigest(),
        "truth_acceleration": "accel_hifi(r, epoch_unix) + exponential-atmosphere drag",
        "estimator_acceleration": "compact two-body + J2 + exponential-atmosphere drag",
        "observed_step_rmse_mean_m": means,
        "paired": paired,
        "pukf_diagnostics": {
            "mean_q_scale": float(np.mean(pukf_q_scales)) if pukf_q_scales else float("nan"),
            "median_q_scale": float(np.median(pukf_q_scales)) if pukf_q_scales else float("nan"),
            "max_q_scale": float(np.max(pukf_q_scales)) if pukf_q_scales else float("nan"),
        },
        "cross_filter_r_only_nis": nis_per_filter,
        "elapsed_seconds": {"truth_generation": float(t_gen), "filters": float(t_filt)},
    }

    out_json = Path(args.output_json)
    out_csv = Path(args.output_csv)
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json.dumps(payload, indent=2))

    rows = []
    for i in range(n_traj):
        row: dict[str, Any] = {"trajectory_index": i}
        for k, arr in metrics.items():
            row[f"{k}_observed_pos_rmse_m"] = float(arr[i]) if np.isfinite(arr[i]) else None
        rows.append(row)
    pd.DataFrame(rows).to_csv(out_csv, index=False)

    print(json.dumps({
        "n_trajectories": int(n_traj),
        "observed_step_rmse_mean_m": means,
        "ekf_minus_aukf_m": paired["EKF_minus_AUKF"]["mean_diff_m"],
        "ekf_minus_aukf_ci": [paired["EKF_minus_AUKF"]["ci_lo_m"], paired["EKF_minus_AUKF"]["ci_hi_m"]],
        "median_r_only_nis": {k: v["median"] for k, v in nis_per_filter.items()},
        "json": str(out_json),
    }, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
