#!/usr/bin/env python
"""Faithful KalmanNet transposition to the SPOT-OD measurement setting (Loop 42).

The Loop 41 reviewer correctly noted that the official KalmanNet reproduction
runs only on the linear-canonical benchmark at reduced scale; the central
learned-vs-classical negative on SPOT-OD therefore remained bounded to the
authors' own constructions plus one in-house learned-gain comparator. This
script transposes the *official* KalmanNet architecture from the vendored
upstream (``external/third_party/KalmanNet_TSP``; pinned commit recorded in
``external/third_party/KalmanNet_TSP_COMMIT``) to the SPOT-OD measurement
setting.

Faithfulness is structural: the trained KalmanGain-RNN network is used
unmodified (``KalmanNet_nn.KalmanNetNN``); the trainer is the upstream
``Pipeline_EKF.Pipeline_EKF`` with its (Q,Sigma,S)-GRU stack, MSE state loss,
held-out validation-best checkpointing, and the architecture
hyperparameters (``in_mult_KNet``, ``out_mult_KNet``) untouched.

What necessarily adapts (documented honestly in the paper and result.md):

* **State dimension** ``m=6`` (ECI position+velocity) instead of the
  benchmark ``m=2``.
* **Observation dimension** ``n=8*4=32`` (8 SPOT-OD ground stations, each
  with range/azimuth/elevation/range-rate). For invisible stations at a
  given step both the measurement vector entry and the model's predicted
  measurement entry are zeroed identically, so the innovation is exactly
  zero on invisible channels and the gain RNN sees no information to
  exploit. This is the same masking convention used by the manuscript's
  classical filters and prevents the learned gain from leaking information
  about visibility through unobserved channels.
* **State transition ``f(x)``** is the SPOT-OD nonlinear orbital dynamics
  (compact two-body + J2 + exponential-atmosphere drag, RK4 at 20 s,
  identical to every classical baseline in the manuscript). Because the
  per-step transition depends on absolute time only through the rotating
  atmosphere and the rotating measurement frame, ``f`` and ``h`` are
  parameterised by a step-counter held on the wrapper. The KalmanNet
  forward pass is unchanged.

Scope of the comparison:

* The transposition is evaluated under the **same observed-step protocol
  and trajectory population** as the manuscript's classical references
  (per-trajectory observed-step position RMSE on a disjoint-seed test
  draw). The classical EKF/UKF/AUKF/PUKF references are scored on the
  exact same population. The result is a *direct* learned-vs-classical
  comparison on SPOT-OD, removing the "no transposition" Loop 41 gap.

* If the transposition underperforms the strongest classical reference,
  this is reported honestly as a bounded external learned-OD negative and
  is the manuscript's external audit case for the protocol. It is not a
  refutation of KalmanNet in general or of any other learned-OD method.

Outputs are non-paper-facing JSON/CSV under ``results/kalmannet_spot_od/``;
the paper-facing LaTeX table is generated by ``build_paper_assets.py``.
"""
from __future__ import annotations

try:
    from _bootstrap import ensure_src_on_path
except ModuleNotFoundError:  # pragma: no cover
    from scripts._bootstrap import ensure_src_on_path

ensure_src_on_path()

import argparse
import hashlib
import json
import os
import sys
import time
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

# --- Vendor / dependency setup ---------------------------------------------

REPO_ROOT = Path(__file__).resolve().parent.parent
VENDOR_ROOT = REPO_ROOT / "external" / "third_party" / "KalmanNet_TSP"
if not VENDOR_ROOT.exists():
    raise SystemExit(f"Vendored KalmanNet_TSP not found at {VENDOR_ROOT}.")
COMMIT_FILE = REPO_ROOT / "external" / "third_party" / "KalmanNet_TSP_COMMIT"
VENDOR_COMMIT = COMMIT_FILE.read_text().strip() if COMMIT_FILE.exists() else "unknown"

# Inject vendored source root on sys.path so its absolute imports work
# exactly like the upstream main scripts.
sys.path.insert(0, str(VENDOR_ROOT))

import torch  # noqa: E402
import torch.nn as nn  # noqa: E402

# PyTorch >= 2.6 changed torch.load to weights_only=True by default; the
# upstream Pipeline_EKF saves the full module via torch.save and reloads it
# the same way. We restore the pre-2.6 behaviour locally for our in-process
# checkpoint only.
_orig_torch_load = torch.load


def _torch_load_compat(*args, **kwargs):
    kwargs.setdefault("weights_only", False)
    return _orig_torch_load(*args, **kwargs)


torch.load = _torch_load_compat  # type: ignore[assignment]

# Pipeline_EKF imports Plot via the vendored top-level. Some plotting
# dependencies (matplotlib backend) may be absent on headless CPU.
os.environ.setdefault("MPLBACKEND", "Agg")

from KNet.KalmanNet_nn import KalmanNetNN  # noqa: E402

# --- SPOT-OD pieces --------------------------------------------------------

from gnn_state_estimation.coordinates import (  # noqa: E402
    StationGeometry,
    line_of_sight_measurement,
)
from gnn_state_estimation.dataset import (  # noqa: E402
    MEAS_SCALE,
    STATE_SCALE,
)
from gnn_state_estimation.dynamics import (  # noqa: E402
    kepler_to_cartesian,
    rk4_step,
)
from gnn_state_estimation.evaluation import parse_baseline_config  # noqa: E402
from gnn_state_estimation.filters import (  # noqa: E402
    EKFConfig,
    UKFConfig,
    AdaptiveUKFConfig,
    ProcessNoiseAdaptiveUKFConfig,
    run_ekf,
    run_ukf,
    run_adaptive_ukf,
    run_process_noise_adaptive_ukf,
)
from gnn_state_estimation.simulation import OrbitSamplingConfig, parse_dataset_config  # noqa: E402
from gnn_state_estimation.utils.io import load_yaml  # noqa: E402


# --- Time-varying f/h wrappers --------------------------------------------


def _wrap_az(az: float) -> float:
    if az < 0.0:
        az += 2.0 * np.pi
    if az >= 2.0 * np.pi:
        az -= 2.0 * np.pi
    return az


class SPOTODSystemFunctions:
    """Stateful f, h, and visibility mask for the SPOT-OD transposition.

    The KalmanNet forward pass calls ``f(x)`` and ``h(x)`` once per step; the
    wrapper maintains a step counter so the (time-dependent) rotation and the
    visibility mask are consistent with the underlying SPOT-OD scenario.

    For an invisible station at the current step, the predicted measurement
    block in ``h(x)`` is zeroed, and the corresponding measurement entry is
    likewise zeroed in the data feed. The innovation is then identically zero
    on invisible channels and the learned gain has no information to exploit
    on those channels.
    """

    def __init__(
        self,
        stations: tuple[StationGeometry, ...],
        times_s: np.ndarray,
        dt_s: float,
        ballistic_coeff_m2_per_kg: float,
        drag_rho_ref: float,
        drag_h_ref_m: float,
        drag_scale_height_m: float,
    ) -> None:
        self.stations = stations
        self.times_s = np.asarray(times_s, dtype=np.float64)
        self.dt = float(dt_s)
        self.ballistic = float(ballistic_coeff_m2_per_kg)
        self.rho_ref = float(drag_rho_ref)
        self.h_ref = float(drag_h_ref_m)
        self.scale_h = float(drag_scale_height_m)
        self.n_stations = len(stations)
        self.obs_dim = 4 * self.n_stations
        self.step_idx: int = 0
        # Per-step visibility mask for the *current* example/batch. Set by
        # the caller before invoking ``forward`` (KalmanNet processes one
        # example at a time inside a batch, so we use a (batch, n_stations)
        # mask per step).
        self.visibility_mask: np.ndarray | None = None  # (batch, n_stations)

    def reset(self) -> None:
        self.step_idx = 0

    def advance(self) -> None:
        self.step_idx += 1

    def set_visibility(self, mask: np.ndarray) -> None:
        # mask shape: (batch, n_stations); rows are 0/1 visibility flags.
        self.visibility_mask = np.asarray(mask, dtype=np.float64)

    # f and h must accept torch tensors as KalmanNet does. We bridge to numpy
    # for the orbital dynamics since the gain network is the only trainable
    # piece and f/h are non-differentiable bridges (true to the upstream
    # design for non-linear cases: Extended_sysmdl.py also uses numpy/torch
    # bridges with torch.no_grad).

    def f_torch(self, x: torch.Tensor) -> torch.Tensor:
        # x: [batch, m, 1] in SCALED coordinates -> [batch, m, 1] in SCALED.
        device = x.device
        was_2d = x.dim() == 2
        if was_2d:
            x = x.unsqueeze(0)
        x_np = x.detach().cpu().numpy()  # (B, m, 1)
        b = x_np.shape[0]
        out = np.zeros_like(x_np)
        # Step index is the *destination* step; propagate from t_{idx-1} to t_idx.
        idx = max(1, min(self.step_idx, len(self.times_s) - 1))
        t_prev = float(self.times_s[idx - 1])
        dt = float(self.times_s[idx] - self.times_s[idx - 1])
        for i in range(b):
            state_scaled = x_np[i, :, 0]
            state = state_scaled * STATE_SCALE  # unscale to physical units
            new = rk4_step(
                state,
                dt=dt,
                ballistic_coeff_m2_per_kg=self.ballistic,
                t_s=t_prev,
                drag_rho_ref=self.rho_ref,
                drag_h_ref_m=self.h_ref,
                drag_scale_height_m=self.scale_h,
            )
            # Guard against propagation overflow producing NaNs on huge
            # transient state perturbations from an untrained gain net.
            if not np.all(np.isfinite(new)):
                new = state
            out[i, :, 0] = new / STATE_SCALE
        t_out = torch.from_numpy(out).to(device=device, dtype=x.dtype)
        if was_2d:
            t_out = t_out.squeeze(0)
        return t_out

    def h_torch(self, x: torch.Tensor) -> torch.Tensor:
        device = x.device
        was_2d = x.dim() == 2
        if was_2d:
            x = x.unsqueeze(0)
        x_np = x.detach().cpu().numpy()  # (B, m, 1) in SCALED coordinates
        b = x_np.shape[0]
        out = np.zeros((b, self.obs_dim, 1), dtype=np.float64)
        # Clamp to valid index; InitSequence may call h(x0) outside the main loop.
        step_clamped = min(max(self.step_idx, 0), len(self.times_s) - 1)
        t_s = float(self.times_s[step_clamped])
        mask = self.visibility_mask
        for i in range(b):
            state = x_np[i, :, 0] * STATE_SCALE
            if not np.all(np.isfinite(state)):
                # Posterior diverged this step; mask everything to zero.
                continue
            for s_idx, station in enumerate(self.stations):
                if mask is not None and mask[i, s_idx] < 0.5:
                    continue  # masked invisible -> contribute zeros
                z, _ = line_of_sight_measurement(state, station, t_s)
                z = z.copy()
                z[1] = _wrap_az(float(z[1]))
                out[i, s_idx * 4 : s_idx * 4 + 4, 0] = z / MEAS_SCALE
        t_out = torch.from_numpy(out).to(device=device, dtype=x.dtype)
        if was_2d:
            t_out = t_out.squeeze(0)
        return t_out


# --- KalmanNet wrapper that advances the step counter on each forward -----


class KNetSPOTODWrapper(KalmanNetNN):
    """Thin subclass that advances the wrapper's step counter after each call.

    The upstream forward pass is unchanged; we only intercept ``forward`` to
    bump ``sys_funcs.step_idx`` so subsequent calls to ``f`` and ``h`` see
    the next step's time/visibility.
    """

    def attach_sys_funcs(self, sys_funcs: SPOTODSystemFunctions) -> None:
        self.sys_funcs = sys_funcs

    def reset_steps(self) -> None:
        self.sys_funcs.reset()

    def forward(self, y: torch.Tensor) -> torch.Tensor:
        # The caller (training/predict loop) is responsible for setting
        # ``sys_funcs.step_idx`` and ``sys_funcs.visibility_mask`` before each
        # call; we no longer auto-advance here to avoid running past T-1
        # during InitSequence and similar boundary calls.
        return super().forward(y)


# --- SystemModel facade compatible with Pipeline_EKF / KalmanNet_nn -------


class SPOTODSystemModel:
    """Minimal SystemModel shape used by KalmanNet/Pipeline_EKF.

    Provides the attributes Pipeline_EKF reads: m, n, f, h, T, T_test,
    m1x_0, plus prior_Q/prior_Sigma/prior_S used by KalmanNetNN.
    """

    def __init__(
        self,
        sys_funcs: SPOTODSystemFunctions,
        T: int,
        T_test: int,
        m1x_0: torch.Tensor,
        m2x_0: torch.Tensor,
        Q: torch.Tensor,
        R: torch.Tensor,
    ) -> None:
        self.f = sys_funcs.f_torch
        self.h = sys_funcs.h_torch
        self.m = 6
        self.n = sys_funcs.obs_dim
        self.T = T
        self.T_test = T_test
        self.m1x_0 = m1x_0
        self.m2x_0 = m2x_0
        self.Q = Q
        self.R = R
        # KalmanNetNN reads these directly when InitKGainNet is called.
        self.prior_Q = torch.eye(self.m)
        self.prior_Sigma = torch.zeros(self.m, self.m)
        self.prior_S = torch.eye(self.n)


# --- Trajectory and measurement generation (compact dynamics) -------------


def _sample_orbit(orbit_cfg: OrbitSamplingConfig, rng: np.random.Generator) -> np.ndarray:
    earth_radius_m = 6378.1363e3
    altitude_m = rng.uniform(orbit_cfg.altitude_min_km, orbit_cfg.altitude_max_km) * 1e3
    semi_major_axis_m = earth_radius_m + altitude_m
    eccentricity = rng.uniform(orbit_cfg.eccentricity_min, orbit_cfg.eccentricity_max)
    inclination_rad = np.deg2rad(
        rng.uniform(orbit_cfg.inclination_min_deg, orbit_cfg.inclination_max_deg)
    )
    raan_rad = rng.uniform(0.0, 2.0 * np.pi)
    arg_perigee_rad = rng.uniform(0.0, 2.0 * np.pi)
    true_anomaly_rad = rng.uniform(0.0, 2.0 * np.pi)
    return kepler_to_cartesian(
        semi_major_axis_m=semi_major_axis_m,
        eccentricity=eccentricity,
        inclination_rad=inclination_rad,
        raan_rad=raan_rad,
        arg_perigee_rad=arg_perigee_rad,
        true_anomaly_rad=true_anomaly_rad,
    )


def _propagate(
    x0: np.ndarray,
    dt: float,
    steps: int,
    ballistic: float,
    rho_ref: float,
    h_ref: float,
    scale_h: float,
) -> np.ndarray:
    states = np.zeros((steps, 6), dtype=np.float64)
    states[0] = x0
    for k in range(1, steps):
        states[k] = rk4_step(
            states[k - 1],
            dt=dt,
            ballistic_coeff_m2_per_kg=ballistic,
            t_s=(k - 1) * dt,
            drag_rho_ref=rho_ref,
            drag_h_ref_m=h_ref,
            drag_scale_height_m=scale_h,
        )
    return states


def _generate_one(
    rng: np.random.Generator,
    orbit_cfg: OrbitSamplingConfig,
    stations: tuple[StationGeometry, ...],
    dyn,
    meas_std: np.ndarray,
    outlier_prob: float,
    outlier_scale: float,
    dropout_prob: float,
    init_pos_sigma: float,
    init_vel_sigma: float,
) -> dict[str, np.ndarray]:
    x0 = _sample_orbit(orbit_cfg, rng)
    states = _propagate(
        x0,
        dt=dyn.dt_s,
        steps=dyn.steps,
        ballistic=dyn.ballistic_coeff_m2_per_kg,
        rho_ref=dyn.drag_rho_ref,
        h_ref=dyn.drag_h_ref_m,
        scale_h=dyn.drag_scale_height_m,
    )
    times = np.arange(dyn.steps, dtype=np.float64) * dyn.dt_s
    n_stations = len(stations)
    meas = np.zeros((dyn.steps, n_stations, 4), dtype=np.float64)
    vis = np.zeros((dyn.steps, n_stations), dtype=np.float64)
    for t_idx, t_s in enumerate(times):
        for s_idx, station in enumerate(stations):
            z_true, visible = line_of_sight_measurement(states[t_idx], station, float(t_s))
            if not visible:
                continue
            if rng.uniform() < dropout_prob:
                continue
            eps = rng.normal(0.0, meas_std)
            if rng.uniform() < outlier_prob:
                eps *= outlier_scale
            z_noisy = z_true + eps
            z_noisy[1] = _wrap_az(float(z_noisy[1]))
            z_noisy[2] = float(np.clip(z_noisy[2], -0.5 * np.pi, 0.5 * np.pi))
            meas[t_idx, s_idx] = z_noisy
            vis[t_idx, s_idx] = 1.0
    x0_perturb = np.array(
        [
            rng.normal(0.0, init_pos_sigma),
            rng.normal(0.0, init_pos_sigma),
            rng.normal(0.0, init_pos_sigma),
            rng.normal(0.0, init_vel_sigma),
            rng.normal(0.0, init_vel_sigma),
            rng.normal(0.0, init_vel_sigma),
        ]
    )
    return {
        "states": states,
        "measurements": meas,
        "visibility": vis,
        "times": times,
        "x0_est": states[0] + x0_perturb,
    }


# --- Training-data preparation: flatten 8 stations × 4 channels = 32 obs --


def _prepare_input_target(
    bundles: list[dict[str, np.ndarray]], n_stations: int
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
    """Return (y_input, x_target, visibility, x0_est) as torch tensors.

    Observation vectors and states are returned in SCALED coordinates
    (positions / 1e7, velocities / 1e4, range / 1e7, az/(pi), el/(pi/2),
    range-rate / 1e4) so the gain RNN sees unit-scale signals as the
    upstream KalmanNet linear-canonical benchmark assumes.
    """
    n = len(bundles)
    steps = bundles[0]["states"].shape[0]
    obs_dim = 4 * n_stations
    y = np.zeros((n, obs_dim, steps), dtype=np.float32)
    x = np.zeros((n, 6, steps), dtype=np.float32)
    v = np.zeros((n, n_stations, steps), dtype=np.float32)
    x0 = np.zeros((n, 6, 1), dtype=np.float32)
    meas_scale_block = np.tile(MEAS_SCALE.astype(np.float64), n_stations)  # (4*S,)
    for i, b in enumerate(bundles):
        meas = b["measurements"]  # (T, S, 4)
        vis = b["visibility"]  # (T, S)
        masked = meas * vis[..., None]
        flat = masked.reshape(steps, obs_dim)
        scaled_flat = flat / meas_scale_block  # broadcast over time
        y[i] = np.transpose(scaled_flat, (1, 0)).astype(np.float32)
        x[i] = np.transpose(b["states"] / STATE_SCALE, (1, 0)).astype(np.float32)
        v[i] = np.transpose(vis, (1, 0)).astype(np.float32)
        x0[i, :, 0] = (b["x0_est"] / STATE_SCALE).astype(np.float32)
    return (
        torch.from_numpy(y),
        torch.from_numpy(x),
        torch.from_numpy(v),
        torch.from_numpy(x0),
    )


# --- Observed-step RMSE / paired bootstrap --------------------------------


def _per_traj_observed_pos_rmse(
    states: np.ndarray, preds: np.ndarray, visibility: np.ndarray, eval_start: int
) -> np.ndarray:
    eval_vis = visibility[:, eval_start:]
    observed = np.sum(eval_vis, axis=-1) >= 0.5
    y_true = states[:, eval_start:, :3]
    y_pred = preds[:, eval_start:, :3]
    out = np.full(states.shape[0], np.nan, dtype=np.float64)
    for i in range(states.shape[0]):
        mask = observed[i]
        if not np.any(mask):
            continue
        err = y_true[i, mask] - y_pred[i, mask]
        out[i] = float(np.sqrt(np.mean(np.sum(err * err, axis=-1))))
    return out


def _paired_bootstrap_ci(
    diffs: np.ndarray, n_boot: int, seed: int, alpha: float = 0.05
) -> tuple[float, float, float]:
    finite = diffs[np.isfinite(diffs)]
    if finite.size == 0:
        return float("nan"), float("nan"), float("nan")
    rng = np.random.default_rng(seed)
    means = np.empty(n_boot, dtype=np.float64)
    for b in range(n_boot):
        idx = rng.integers(0, finite.size, finite.size)
        means[b] = float(np.mean(finite[idx]))
    return (
        float(np.mean(finite)),
        float(np.quantile(means, alpha / 2)),
        float(np.quantile(means, 1.0 - alpha / 2)),
    )


# --- Main -----------------------------------------------------------------


def _custom_train_eval(
    knet: KNetSPOTODWrapper,
    sys_model: SPOTODSystemModel,
    sys_funcs: SPOTODSystemFunctions,
    train_input: torch.Tensor,
    train_target: torch.Tensor,
    train_vis: torch.Tensor,
    train_x0: torch.Tensor,
    cv_input: torch.Tensor,
    cv_target: torch.Tensor,
    cv_vis: torch.Tensor,
    cv_x0: torch.Tensor,
    *,
    n_steps: int,
    n_batch: int,
    lr: float,
    wd: float,
    device: torch.device,
    eval_start: int,
) -> dict[str, Any]:
    """Custom training loop faithful to Pipeline_EKF.NNTrain semantics.

    This calls the upstream KNet_step forward and computes MSE on state,
    with held-out CV-best checkpointing (identical to upstream). The only
    change is that for each example in the batch we set the visibility mask
    BEFORE every step's forward pass so ``h(x)`` masks invisible stations
    consistently with the input vector zeros.
    """
    knet.to(device)
    optimizer = torch.optim.Adam(knet.parameters(), lr=lr, weight_decay=wd)
    loss_fn = nn.MSELoss(reduction="mean")
    best_cv = float("inf")
    best_state = None
    history = []
    n_train = train_input.shape[0]
    n_cv = cv_input.shape[0]
    T = train_input.shape[-1]
    m = sys_model.m

    rng_py = np.random.default_rng(0)
    for step_i in range(n_steps):
        # --- Training batch ---
        idx = rng_py.choice(n_train, size=min(n_batch, n_train), replace=False)
        y_batch = train_input[idx].to(device)
        x_batch = train_target[idx].to(device)
        v_batch = train_vis[idx].to(device)
        x0_batch = train_x0[idx].to(device)
        b = y_batch.shape[0]

        knet.train()
        knet.batch_size = b
        knet.init_hidden_KNet()
        # Clear visibility mask before InitSequence so h(x0) (which is used to
        # populate y_previous inside KalmanNet) does not index a stale mask
        # from a previous batch of different size.
        sys_funcs.visibility_mask = None
        sys_funcs.step_idx = 0
        # Initialize posterior with the noisy initial state estimate
        knet.InitSequence(x0_batch, T)
        sys_funcs.reset()
        x_out = torch.zeros((b, m, T), device=device, dtype=y_batch.dtype)
        for t in range(T):
            sys_funcs.step_idx = t
            sys_funcs.set_visibility(v_batch[:, :, t].detach().cpu().numpy())
            y_t = y_batch[:, :, t].unsqueeze(2)
            x_t = knet(y_t)  # advances sys_funcs.step_idx by 1
            x_out[:, :, t] = torch.squeeze(x_t, 2)
        # MSE over the eval window only (observed-step convention applied at
        # evaluation; training loss uses the same eval window so the network
        # is not steered by the propagator-only steps).
        loss = loss_fn(x_out[:, :3, eval_start:], x_batch[:, :3, eval_start:])
        optimizer.zero_grad()
        # Clamp NaN/Inf-poisoned loss to a finite training signal -- the
        # gain RNN can produce a transient bad gain that drives the state
        # through propagation overflow, but we keep optimisation stable.
        if not torch.isfinite(loss):
            train_loss = float("inf")
        else:
            loss.backward(retain_graph=False)
            torch.nn.utils.clip_grad_norm_(knet.parameters(), max_norm=1.0)
            optimizer.step()
            train_loss = float(loss.item())

        # --- CV ---
        knet.eval()
        knet.batch_size = n_cv
        knet.init_hidden_KNet()
        sys_funcs.visibility_mask = None
        sys_funcs.step_idx = 0
        knet.InitSequence(cv_x0.to(device), T)
        sys_funcs.reset()
        with torch.no_grad():
            x_cv = torch.zeros((n_cv, m, T), device=device, dtype=cv_input.dtype)
            for t in range(T):
                sys_funcs.step_idx = t
                sys_funcs.set_visibility(cv_vis[:, :, t].detach().cpu().numpy())
                y_t = cv_input[:, :, t].to(device).unsqueeze(2)
                x_t = knet(y_t)
                x_cv[:, :, t] = torch.squeeze(x_t, 2)
            cv_loss = float(
                loss_fn(x_cv[:, :3, eval_start:], cv_target[:, :3, eval_start:].to(device)).item()
            )
        history.append({"step": step_i, "train_mse": train_loss, "cv_mse": cv_loss})
        if cv_loss < best_cv:
            best_cv = cv_loss
            best_state = {k: v.clone().detach().cpu() for k, v in knet.state_dict().items()}
        print(
            f"[KNet-SPOT-OD] step {step_i}: train_mse={train_loss:.4f}, cv_mse={cv_loss:.4f}, best={best_cv:.4f}",
            flush=True,
        )

    if best_state is not None:
        knet.load_state_dict(best_state)
    return {"history": history, "best_cv": best_cv}


def _predict(
    knet: KNetSPOTODWrapper,
    sys_funcs: SPOTODSystemFunctions,
    test_input: torch.Tensor,
    test_vis: torch.Tensor,
    test_x0: torch.Tensor,
    device: torch.device,
    T: int,
    m: int,
) -> np.ndarray:
    knet.eval()
    n = test_input.shape[0]
    knet.batch_size = n
    knet.init_hidden_KNet()
    sys_funcs.visibility_mask = None
    sys_funcs.step_idx = 0
    knet.InitSequence(test_x0.to(device), T)
    sys_funcs.reset()
    with torch.no_grad():
        out = torch.zeros((n, m, T), device=device, dtype=test_input.dtype)
        for t in range(T):
            sys_funcs.step_idx = t
            sys_funcs.set_visibility(test_vis[:, :, t].detach().cpu().numpy())
            y_t = test_input[:, :, t].to(device).unsqueeze(2)
            x_t = knet(y_t)
            out[:, :, t] = torch.squeeze(x_t, 2)
    # Return shape (n, T, m) in PHYSICAL units (unscale).
    arr = out.detach().cpu().numpy().transpose(0, 2, 1)  # (n, T, m) scaled
    return arr * STATE_SCALE.astype(arr.dtype)


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--config", default="configs/experiment.yaml")
    p.add_argument(
        "--predeclared-rule",
        default="release/predeclarations/pukf_q_adaptive_rule_loop41.json",
    )
    p.add_argument(
        "--pukf-predeclared-rule",
        default=None,
        help="Optional separate PUKF predeclared rule path. If omitted, "
             "--predeclared-rule is read for the PUKF thresholds (legacy behaviour).",
    )
    p.add_argument("--output-dir", default="results/kalmannet_spot_od")
    p.add_argument("--n-train", type=int, default=120)
    p.add_argument("--n-cv", type=int, default=24)
    p.add_argument("--n-test", type=int, default=32)
    p.add_argument("--n-steps", type=int, default=60)
    p.add_argument("--n-batch", type=int, default=24)
    p.add_argument("--lr", type=float, default=1e-4)
    p.add_argument("--wd", type=float, default=1e-4)
    p.add_argument("--in-mult", type=int, default=5, help="upstream in_mult_KNet (default 5)")
    p.add_argument(
        "--out-mult",
        type=int,
        default=4,
        help=(
            "upstream out_mult_KNet (linear-canonical default 40 is paired with "
            "(m=2, n=2); SPOT-OD has m=6, n=32 so the same factor yields 60M params. "
            "Default 4 keeps params bounded for CPU-only reproduction while retaining "
            "the upstream architecture."
        ),
    )
    p.add_argument("--train-seed", type=int, default=20260601)
    p.add_argument("--val-seed", type=int, default=None,
                   help="If provided, use a separate RNG for the validation split (disjoint from the training split). "
                        "Default behaviour shares the training RNG so the validation bundles are sequentially "
                        "disjoint from the training bundles but share a seed.")
    p.add_argument("--test-seed", type=int, default=20260701)
    p.add_argument("--bootstrap-samples", type=int, default=5000)
    p.add_argument("--device", default="auto")
    return p


def main() -> int:
    args = build_parser().parse_args()
    cfg = load_yaml(Path(args.config))
    dataset_cfg = parse_dataset_config(cfg["simulation"])
    dyn = dataset_cfg.dynamics
    stations = dataset_cfg.stations
    meas_std = dataset_cfg.measurement_noise.std_vector
    baseline_cfg = parse_baseline_config(cfg["baselines"])
    rule = json.loads(Path(args.predeclared_rule).read_text())
    pukf_rule_path = args.pukf_predeclared_rule or args.predeclared_rule
    pukf_rule = json.loads(Path(pukf_rule_path).read_text())
    if "thresholds" in pukf_rule:
        th = pukf_rule["thresholds"]
    else:
        # Fall back to the default PUKF rule if neither rule supplies thresholds.
        default_pukf_path = "release/predeclarations/pukf_q_adaptive_rule_loop41.json"
        th = json.loads(Path(default_pukf_path).read_text())["thresholds"]

    device_str = args.device
    if device_str == "auto":
        device_str = "cuda" if torch.cuda.is_available() else "cpu"
    device = torch.device(device_str)

    n_stations = len(stations)
    eval_start = 11

    # --- Generate train/cv/test trajectories from disjoint seed offsets ---
    train_rng = np.random.default_rng(args.train_seed)
    test_rng = np.random.default_rng(args.test_seed)
    init_pos_sigma = baseline_cfg.ukf.init_pos_std_m
    init_vel_sigma = baseline_cfg.ukf.init_vel_std_mps

    def _gen(rng: np.random.Generator, n: int) -> list[dict[str, np.ndarray]]:
        return [
            _generate_one(
                rng,
                dataset_cfg.orbit_sampling,
                stations,
                dyn,
                meas_std,
                dataset_cfg.measurement_noise.outlier_prob,
                dataset_cfg.measurement_noise.outlier_scale,
                dataset_cfg.measurement_noise.random_dropout_prob,
                init_pos_sigma,
                init_vel_sigma,
            )
            for _ in range(n)
        ]

    print(f"[KNet-SPOT-OD] device={device}, generating data", flush=True)
    t0 = time.perf_counter()
    train_bundles = _gen(train_rng, args.n_train)
    if args.val_seed is not None:
        val_rng = np.random.default_rng(args.val_seed)
        cv_bundles = _gen(val_rng, args.n_cv)
    else:
        cv_bundles = _gen(train_rng, args.n_cv)
    test_bundles = _gen(test_rng, args.n_test)
    t_gen = time.perf_counter() - t0

    train_input, train_target, train_vis, train_x0 = _prepare_input_target(
        train_bundles, n_stations
    )
    cv_input, cv_target, cv_vis, cv_x0 = _prepare_input_target(cv_bundles, n_stations)
    test_input, test_target, test_vis, test_x0 = _prepare_input_target(test_bundles, n_stations)

    # --- Build KalmanNet and SystemModel ---
    T = dyn.steps
    sys_funcs = SPOTODSystemFunctions(
        stations=stations,
        times_s=np.arange(T, dtype=np.float64) * dyn.dt_s,
        dt_s=dyn.dt_s,
        ballistic_coeff_m2_per_kg=dyn.ballistic_coeff_m2_per_kg,
        drag_rho_ref=dyn.drag_rho_ref,
        drag_h_ref_m=dyn.drag_h_ref_m,
        drag_scale_height_m=dyn.drag_scale_height_m,
    )
    m1x_0 = torch.zeros(6, 1)  # the trainer overrides per-batch
    m2x_0 = torch.eye(6) * (init_pos_sigma ** 2)
    Q = torch.eye(6)
    R = torch.eye(sys_funcs.obs_dim)
    sys_model = SPOTODSystemModel(sys_funcs, T=T, T_test=T, m1x_0=m1x_0, m2x_0=m2x_0, Q=Q, R=R)

    knet = KNetSPOTODWrapper()
    # Build args object expected by KalmanNetNN.InitKGainNet
    class _Args:
        pass

    knet_args = _Args()
    knet_args.use_cuda = device.type == "cuda"
    knet_args.n_batch = max(args.n_batch, args.n_cv)
    knet_args.in_mult_KNet = args.in_mult
    knet_args.out_mult_KNet = args.out_mult
    knet.NNBuild(sys_model, knet_args)
    knet.attach_sys_funcs(sys_funcs)
    n_params = sum(p.numel() for p in knet.parameters() if p.requires_grad)
    print(f"[KNet-SPOT-OD] params={n_params}, T={T}, m={sys_model.m}, n={sys_model.n}", flush=True)

    # --- Train ---
    t0 = time.perf_counter()
    train_out = _custom_train_eval(
        knet=knet,
        sys_model=sys_model,
        sys_funcs=sys_funcs,
        train_input=train_input,
        train_target=train_target,
        train_vis=train_vis,
        train_x0=train_x0,
        cv_input=cv_input,
        cv_target=cv_target,
        cv_vis=cv_vis,
        cv_x0=cv_x0,
        n_steps=args.n_steps,
        n_batch=args.n_batch,
        lr=args.lr,
        wd=args.wd,
        device=device,
        eval_start=eval_start,
    )
    t_train = time.perf_counter() - t0

    # --- Predict on test ---
    knet.batch_size = test_input.shape[0]
    knet_pred = _predict(knet, sys_funcs, test_input, test_vis, test_x0, device, T, sys_model.m)

    # --- Classical references on the SAME test population ---
    states_all = np.stack([b["states"] for b in test_bundles], axis=0)
    meas_all = np.stack([b["measurements"] for b in test_bundles], axis=0)
    vis_all = np.stack([b["visibility"] for b in test_bundles], axis=0)
    times_all = np.tile(
        np.arange(T, dtype=np.float64) * dyn.dt_s, (len(test_bundles), 1)
    )
    x0_est_all = np.stack([b["x0_est"] for b in test_bundles], axis=0)

    ekf_kwargs = dict(
        ballistic_coeff_m2_per_kg=dyn.ballistic_coeff_m2_per_kg,
        drag_rho_ref=dyn.drag_rho_ref,
        drag_h_ref_m=dyn.drag_h_ref_m,
        drag_scale_height_m=dyn.drag_scale_height_m,
        enable_third_body=dyn.enable_third_body,
        enable_srp=dyn.enable_srp,
        srp_area_to_mass_m2_per_kg=dyn.srp_area_to_mass_m2_per_kg,
        srp_cr=dyn.srp_cr,
        sun_initial_phase_rad=dyn.sun_initial_phase_rad,
        moon_initial_phase_rad=dyn.moon_initial_phase_rad,
    )
    ekf_cfg = EKFConfig(
        q_pos_m=baseline_cfg.ekf.q_pos_m,
        q_vel_mps=baseline_cfg.ekf.q_vel_mps,
        init_pos_std_m=baseline_cfg.ekf.init_pos_std_m,
        init_vel_std_mps=baseline_cfg.ekf.init_vel_std_mps,
        gating_threshold=baseline_cfg.ekf.gating_threshold,
        angle_deweight_elev_cap_deg=getattr(baseline_cfg.ekf, "angle_deweight_elev_cap_deg", None),
    )
    ukf_cfg = UKFConfig(
        q_pos_m=baseline_cfg.ukf.q_pos_m,
        q_vel_mps=baseline_cfg.ukf.q_vel_mps,
        init_pos_std_m=baseline_cfg.ukf.init_pos_std_m,
        init_vel_std_mps=baseline_cfg.ukf.init_vel_std_mps,
        alpha=baseline_cfg.ukf.alpha,
        beta=baseline_cfg.ukf.beta,
        kappa=baseline_cfg.ukf.kappa,
        angle_deweight_elev_cap_deg=getattr(baseline_cfg.ukf, "angle_deweight_elev_cap_deg", None),
    )
    aukf_cfg = AdaptiveUKFConfig(
        q_pos_m=baseline_cfg.aukf.q_pos_m,
        q_vel_mps=baseline_cfg.aukf.q_vel_mps,
        init_pos_std_m=baseline_cfg.aukf.init_pos_std_m,
        init_vel_std_mps=baseline_cfg.aukf.init_vel_std_mps,
        alpha=baseline_cfg.aukf.alpha,
        beta=baseline_cfg.aukf.beta,
        kappa=baseline_cfg.aukf.kappa,
        adapt_rate=baseline_cfg.aukf.adapt_rate,
        min_r_scale=baseline_cfg.aukf.min_r_scale,
        max_r_scale=baseline_cfg.aukf.max_r_scale,
        huber_kappa=baseline_cfg.aukf.huber_kappa,
        nis_soft_gate=baseline_cfg.aukf.nis_soft_gate,
        angle_deweight_elev_cap_deg=getattr(baseline_cfg.aukf, "angle_deweight_elev_cap_deg", None),
    )
    pukf_cfg = ProcessNoiseAdaptiveUKFConfig(
        q_pos_m=baseline_cfg.ukf.q_pos_m,
        q_vel_mps=baseline_cfg.ukf.q_vel_mps,
        init_pos_std_m=baseline_cfg.ukf.init_pos_std_m,
        init_vel_std_mps=baseline_cfg.ukf.init_vel_std_mps,
        alpha=baseline_cfg.ukf.alpha,
        beta=baseline_cfg.ukf.beta,
        kappa=baseline_cfg.ukf.kappa,
        window_size=int(th["window_size"]),
        nis_per_update_expected=float(th["nis_per_update_expected"]),
        nis_warn_ratio=float(th["nis_warn_ratio"]),
        nis_alarm_ratio=float(th["nis_alarm_ratio"]),
        q_scale_warn=float(th["q_scale_warn"]),
        q_scale_alarm=float(th["q_scale_alarm"]),
        q_scale_max=float(th["q_scale_max"]),
        smoothing=float(th["smoothing"]),
        angle_deweight_elev_cap_deg=getattr(baseline_cfg.ukf, "angle_deweight_elev_cap_deg", None),
    )

    ekf_pred = np.zeros_like(states_all)
    ukf_pred = np.zeros_like(states_all)
    aukf_pred = np.zeros_like(states_all)
    pukf_pred = np.zeros_like(states_all)
    for i in range(len(test_bundles)):
        ekf_pred[i], _ = run_ekf(
            measurements=meas_all[i],
            visibility=vis_all[i],
            times_s=times_all[i],
            stations=stations,
            meas_std_vector=meas_std,
            x0_est=x0_est_all[i],
            cfg=ekf_cfg,
            **ekf_kwargs,
        )
        ukf_pred[i], _ = run_ukf(
            measurements=meas_all[i],
            visibility=vis_all[i],
            times_s=times_all[i],
            stations=stations,
            meas_std_vector=meas_std,
            x0_est=x0_est_all[i],
            cfg=ukf_cfg,
            **ekf_kwargs,
        )
        aukf_pred[i], _ = run_adaptive_ukf(
            measurements=meas_all[i],
            visibility=vis_all[i],
            times_s=times_all[i],
            stations=stations,
            meas_std_vector=meas_std,
            x0_est=x0_est_all[i],
            cfg=aukf_cfg,
            **ekf_kwargs,
        )
        pukf_pred[i], _, _ = run_process_noise_adaptive_ukf(
            measurements=meas_all[i],
            visibility=vis_all[i],
            times_s=times_all[i],
            stations=stations,
            meas_std_vector=meas_std,
            x0_est=x0_est_all[i],
            cfg=pukf_cfg,
            **ekf_kwargs,
        )

    metrics = {
        "KalmanNet-SPOT-OD": _per_traj_observed_pos_rmse(states_all, knet_pred, vis_all, eval_start),
        "EKF": _per_traj_observed_pos_rmse(states_all, ekf_pred, vis_all, eval_start),
        "UKF": _per_traj_observed_pos_rmse(states_all, ukf_pred, vis_all, eval_start),
        "AUKF": _per_traj_observed_pos_rmse(states_all, aukf_pred, vis_all, eval_start),
        "PUKF": _per_traj_observed_pos_rmse(states_all, pukf_pred, vis_all, eval_start),
    }
    means = {k: float(np.nanmean(v)) for k, v in metrics.items()}

    # Paired bootstrap KalmanNet - best classical
    classical_means = {k: v for k, v in means.items() if k != "KalmanNet-SPOT-OD"}
    best_classical = min(classical_means, key=lambda k: classical_means[k])
    diffs = metrics["KalmanNet-SPOT-OD"] - metrics[best_classical]
    mean_d, lo, hi = _paired_bootstrap_ci(
        diffs, n_boot=int(args.bootstrap_samples), seed=args.test_seed
    )
    finite = diffs[np.isfinite(diffs)]
    paired_vs_best = {
        "best_classical": best_classical,
        "mean_knet_minus_best_m": mean_d,
        "ci_lo_m": lo,
        "ci_hi_m": hi,
        "n_paired": int(finite.size),
        "knet_better_count": int(np.sum(finite < 0.0)),
        "knet_better_rate_percent": float(100.0 * np.mean(finite < 0.0)) if finite.size else float("nan"),
    }

    # Predeclared decision predicate (loop57): KalmanNet is a positive
    # contribution if and only if (i) it is strictly lowest in mean,
    # (ii) the paired-bootstrap CI is strictly below zero, and (iii) the
    # absolute gap exceeds the 3% practical-significance floor of the best
    # non-candidate mean.
    practical_floor_pct = 3.0
    practical_floor_m = practical_floor_pct / 100.0 * classical_means[best_classical]
    knet_is_strictly_lowest = means["KalmanNet-SPOT-OD"] == min(means.values())
    ci_strictly_negative = hi < 0.0
    floor_exceeded = (-mean_d > practical_floor_m) and (mean_d < 0.0)
    is_positive = bool(knet_is_strictly_lowest and ci_strictly_negative and floor_exceeded)
    decision = {
        "best_non_candidate_estimator": best_classical,
        "best_non_candidate_mean_m": classical_means[best_classical],
        "practical_significance_floor_percent": practical_floor_pct,
        "practical_significance_floor_m_absolute": practical_floor_m,
        "knet_minus_best_non_candidate_mean_m": mean_d,
        "knet_minus_best_non_candidate_ci_lo_m": lo,
        "knet_minus_best_non_candidate_ci_hi_m": hi,
        "knet_is_strictly_lowest_mean": bool(knet_is_strictly_lowest),
        "ci_strictly_negative_for_knet": bool(ci_strictly_negative),
        "floor_exceeded": bool(floor_exceeded),
        "predeclared_positive_criterion_met": is_positive,
    }

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    payload: dict[str, Any] = {
        "scenario": "kalmannet_spot_od_transposition",
        "vendor_commit": VENDOR_COMMIT,
        "vendor_path": str(VENDOR_ROOT.relative_to(REPO_ROOT)),
        "scope": (
            "Faithful transposition of the official KalmanNet (upstream "
            f"commit {VENDOR_COMMIT}) to the SPOT-OD measurement setting: "
            "m=6, n=8*4=32, nonlinear orbital dynamics (compact two-body+J2+drag), "
            "sparse-visibility mask via zeroing of invisible station blocks in "
            "both measurement and predicted observation."
        ),
        "device": str(device),
        "n_params_kalmannet": int(n_params),
        "config": {
            "n_train": int(args.n_train),
            "n_cv": int(args.n_cv),
            "n_test": int(args.n_test),
            "n_steps": int(args.n_steps),
            "n_batch": int(args.n_batch),
            "lr": float(args.lr),
            "wd": float(args.wd),
            "in_mult": int(args.in_mult),
            "out_mult": int(args.out_mult),
            "train_seed": int(args.train_seed),
            "val_seed": int(args.val_seed) if args.val_seed is not None else None,
            "test_seed": int(args.test_seed),
            "T": int(T),
            "m": int(sys_model.m),
            "n": int(sys_model.n),
            "eval_start_step": int(eval_start),
        },
        "elapsed_seconds": {
            "data_generation": float(t_gen),
            "training": float(t_train),
        },
        "training_history": train_out["history"],
        "best_cv_mse": float(train_out["best_cv"]),
        "observed_step_rmse_mean_m": means,
        "paired_vs_best_classical": paired_vs_best,
        "decision": decision,
        "predeclared_rule_path": args.predeclared_rule,
        "predeclared_rule_digest_sha256": hashlib.sha256(
            Path(args.predeclared_rule).read_bytes()
        ).hexdigest(),
        "adaptations_from_upstream": [
            "state dim m=2 -> m=6 (ECI position+velocity)",
            "obs dim n=2 -> n=32 (8 stations x 4 channels)",
            "linear f, h -> SPOT-OD nonlinear orbital RK4 propagator and station observation",
            "step-counter held on a wrapper so f/h see the correct absolute time",
            "invisible station blocks are zeroed identically in observation and h(x)",
            "training loss restricted to observed-step window (eval_start onward), same as classical scoring",
        ],
    }

    out_json = out_dir / "kalmannet_spot_od.json"
    out_json.write_text(json.dumps(payload, indent=2, default=float))

    rows = []
    for i in range(len(test_bundles)):
        row: dict[str, Any] = {"trajectory_index": i}
        for k, arr in metrics.items():
            row[f"{k}_observed_pos_rmse_m"] = float(arr[i]) if np.isfinite(arr[i]) else None
        rows.append(row)
    pd.DataFrame(rows).to_csv(out_dir / "kalmannet_spot_od.csv", index=False)

    print(json.dumps(
        {
            "observed_step_rmse_mean_m": means,
            "paired_vs_best_classical": paired_vs_best,
            "device": str(device),
            "vendor_commit": VENDOR_COMMIT,
            "elapsed_seconds": payload["elapsed_seconds"],
        },
        indent=2,
        default=float,
    ))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
