#!/usr/bin/env python
"""Budget-adequacy diagnostic for the faithful KalmanNet SPOT-OD transposition.

This driver re-runs the loop57 faithful KalmanNet SPOT-OD transposition
under a materially larger optimizer-step budget with snapshots committed
in advance, so the post-loop57 reviewer concern about budget adequacy is
answered with an evidential learning curve rather than a single-budget
point estimate.

The data layout (train/validation/test seeds and sizes), the upstream
architecture (vendored KalmanNet at the recorded commit, gain network
unchanged), the four predeclared loop57 design changes (orbital-scale
normalisation, sequence-length and curriculum rematching, sparse-
observation architectural adaptation, learning-rate and budget
recalibration), and the predeclared decision predicate (KalmanNet
strictly lowest mean, paired-bootstrap CI strictly below zero, absolute
gap exceeding the 3% practical-significance floor of the best non-
candidate mean) are taken byte-identical from the loop57 transposition
rule. Only the optimizer-step budget is varied and only along the
predeclared snapshot schedule recorded in
``release/predeclarations/kalmannet_spot_od_budget_adequacy_loop58.json``.

Outputs (non-paper-facing artefacts):
  - ``results/kalmannet_spot_od_budget_adequacy_loop58/kalmannet_spot_od_budget_adequacy.json``
  - ``results/kalmannet_spot_od_budget_adequacy_loop58/kalmannet_spot_od_budget_adequacy.csv``

The paper-facing supplement table is generated by ``build_paper_assets.py``.
"""
from __future__ import annotations

try:
    from _bootstrap import ensure_src_on_path
except ModuleNotFoundError:  # pragma: no cover
    from scripts._bootstrap import ensure_src_on_path

ensure_src_on_path()

import argparse
import hashlib
import json
import time
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

import run_kalmannet_spot_od_transposition as base

import torch  # noqa: E402
import torch.nn as nn  # noqa: E402

from gnn_state_estimation.evaluation import parse_baseline_config  # noqa: E402
from gnn_state_estimation.filters import (  # noqa: E402
    EKFConfig,
    UKFConfig,
    AdaptiveUKFConfig,
    ProcessNoiseAdaptiveUKFConfig,
    run_ekf,
    run_ukf,
    run_adaptive_ukf,
    run_process_noise_adaptive_ukf,
)
from gnn_state_estimation.simulation import parse_dataset_config  # noqa: E402
from gnn_state_estimation.utils.io import load_yaml  # noqa: E402


def _train_with_snapshots(
    knet: base.KNetSPOTODWrapper,
    sys_model: base.SPOTODSystemModel,
    sys_funcs: base.SPOTODSystemFunctions,
    train_input: torch.Tensor,
    train_target: torch.Tensor,
    train_vis: torch.Tensor,
    train_x0: torch.Tensor,
    cv_input: torch.Tensor,
    cv_target: torch.Tensor,
    cv_vis: torch.Tensor,
    cv_x0: torch.Tensor,
    *,
    n_steps: int,
    n_batch: int,
    lr: float,
    wd: float,
    device: torch.device,
    eval_start: int,
    snapshot_steps: list[int],
) -> dict[str, Any]:
    """Single training run with state-dict snapshots captured immediately
    after the optimizer step at each milestone in ``snapshot_steps``.

    The training loop is structurally identical to the loop57 trainer
    (``base._custom_train_eval``): same batch sampler RNG, same loss, same
    NaN/Inf guard, same gradient clipping, same Adam(lr, wd). The only
    differences are (i) we step up to ``n_steps`` (>= 300, the loop57
    budget) and (ii) we capture state-dicts at the predeclared milestones.
    """
    knet.to(device)
    optimizer = torch.optim.Adam(knet.parameters(), lr=lr, weight_decay=wd)
    loss_fn = nn.MSELoss(reduction="mean")
    best_cv = float("inf")
    history: list[dict[str, Any]] = []
    snapshots: dict[int, dict[str, torch.Tensor]] = {}
    snapshot_cv: dict[int, float] = {}
    snapshot_train: dict[int, float] = {}
    snapshot_set = set(int(s) for s in snapshot_steps)
    n_train = train_input.shape[0]
    n_cv = cv_input.shape[0]
    T = train_input.shape[-1]
    m = sys_model.m

    rng_py = np.random.default_rng(0)
    for step_i in range(n_steps):
        idx = rng_py.choice(n_train, size=min(n_batch, n_train), replace=False)
        y_batch = train_input[idx].to(device)
        x_batch = train_target[idx].to(device)
        v_batch = train_vis[idx].to(device)
        x0_batch = train_x0[idx].to(device)
        b = y_batch.shape[0]

        knet.train()
        knet.batch_size = b
        knet.init_hidden_KNet()
        sys_funcs.visibility_mask = None
        sys_funcs.step_idx = 0
        knet.InitSequence(x0_batch, T)
        sys_funcs.reset()
        x_out = torch.zeros((b, m, T), device=device, dtype=y_batch.dtype)
        for t in range(T):
            sys_funcs.step_idx = t
            sys_funcs.set_visibility(v_batch[:, :, t].detach().cpu().numpy())
            y_t = y_batch[:, :, t].unsqueeze(2)
            x_t = knet(y_t)
            x_out[:, :, t] = torch.squeeze(x_t, 2)
        loss = loss_fn(x_out[:, :3, eval_start:], x_batch[:, :3, eval_start:])
        optimizer.zero_grad()
        if not torch.isfinite(loss):
            train_loss = float("inf")
        else:
            loss.backward(retain_graph=False)
            torch.nn.utils.clip_grad_norm_(knet.parameters(), max_norm=1.0)
            optimizer.step()
            train_loss = float(loss.item())

        knet.eval()
        knet.batch_size = n_cv
        knet.init_hidden_KNet()
        sys_funcs.visibility_mask = None
        sys_funcs.step_idx = 0
        knet.InitSequence(cv_x0.to(device), T)
        sys_funcs.reset()
        with torch.no_grad():
            x_cv = torch.zeros((n_cv, m, T), device=device, dtype=cv_input.dtype)
            for t in range(T):
                sys_funcs.step_idx = t
                sys_funcs.set_visibility(cv_vis[:, :, t].detach().cpu().numpy())
                y_t = cv_input[:, :, t].to(device).unsqueeze(2)
                x_t = knet(y_t)
                x_cv[:, :, t] = torch.squeeze(x_t, 2)
            cv_loss = float(
                loss_fn(x_cv[:, :3, eval_start:], cv_target[:, :3, eval_start:].to(device)).item()
            )
        history.append({"step": step_i, "train_mse": train_loss, "cv_mse": cv_loss})
        if cv_loss < best_cv:
            best_cv = cv_loss

        completed_step = step_i + 1
        if completed_step in snapshot_set:
            snapshots[completed_step] = {
                k: v.clone().detach().cpu() for k, v in knet.state_dict().items()
            }
            snapshot_cv[completed_step] = cv_loss
            snapshot_train[completed_step] = train_loss
            print(
                f"[KNet-BA] snapshot at step {completed_step}: "
                f"train_mse={train_loss:.6e}, cv_mse={cv_loss:.6e}, best_cv={best_cv:.6e}",
                flush=True,
            )
        elif completed_step % 50 == 0 or completed_step == 1:
            print(
                f"[KNet-BA] step {completed_step}: "
                f"train_mse={train_loss:.6e}, cv_mse={cv_loss:.6e}, best={best_cv:.6e}",
                flush=True,
            )

    return {
        "history": history,
        "best_cv": best_cv,
        "snapshots": snapshots,
        "snapshot_cv": snapshot_cv,
        "snapshot_train": snapshot_train,
    }


def _eval_snapshot(
    knet: base.KNetSPOTODWrapper,
    sys_funcs: base.SPOTODSystemFunctions,
    state_dict: dict[str, torch.Tensor],
    test_input: torch.Tensor,
    test_vis: torch.Tensor,
    test_x0: torch.Tensor,
    device: torch.device,
    T: int,
    m: int,
    states_all: np.ndarray,
    vis_all: np.ndarray,
    eval_start: int,
) -> np.ndarray:
    knet.load_state_dict({k: v.to(device) for k, v in state_dict.items()})
    knet.batch_size = test_input.shape[0]
    preds = base._predict(knet, sys_funcs, test_input, test_vis, test_x0, device, T, m)
    return base._per_traj_observed_pos_rmse(states_all, preds, vis_all, eval_start)


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--config", default="configs/experiment.yaml")
    p.add_argument(
        "--predeclared-rule",
        default="release/predeclarations/kalmannet_spot_od_budget_adequacy_loop58.json",
    )
    p.add_argument(
        "--pukf-predeclared-rule",
        default="release/predeclarations/pukf_q_adaptive_rule_loop41.json",
    )
    p.add_argument(
        "--output-dir",
        default="results/kalmannet_spot_od_budget_adequacy_loop58",
    )
    return p


def main() -> int:
    args = build_parser().parse_args()
    cfg = load_yaml(Path(args.config))
    dataset_cfg = parse_dataset_config(cfg["simulation"])
    dyn = dataset_cfg.dynamics
    stations = dataset_cfg.stations
    meas_std = dataset_cfg.measurement_noise.std_vector
    baseline_cfg = parse_baseline_config(cfg["baselines"])
    rule = json.loads(Path(args.predeclared_rule).read_text())
    pukf_rule = json.loads(Path(args.pukf_predeclared_rule).read_text())
    th = pukf_rule["thresholds"]

    n_train = int(rule["data"]["train_split"]["n_trajectories"])
    n_cv = int(rule["data"]["validation_split"]["n_trajectories"])
    n_test = int(rule["data"]["test_split"]["n_trajectories"])
    train_seed = int(rule["data"]["train_split"]["rng_seed"])
    val_seed = int(rule["data"]["validation_split"]["rng_seed"])
    test_seed = int(rule["data"]["test_split"]["rng_seed"])

    pb = rule["predeclared_optimisation_budget"]
    n_steps = int(pb["n_steps_total"])
    n_batch = int(pb["n_batch"])
    lr = float(pb["lr"])
    wd = float(pb["wd"])
    in_mult = int(pb["in_mult_KNet"])
    out_mult = int(pb["out_mult_KNet"])
    snapshot_steps = sorted(set(int(s) for s in pb["predeclared_snapshot_schedule"]))
    if max(snapshot_steps) > n_steps:
        raise SystemExit(
            f"Final predeclared snapshot {max(snapshot_steps)} exceeds n_steps_total {n_steps}."
        )

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    if device.type != "cuda":
        # The rule predeclares CUDA; abort honestly on CPU so a CPU run is
        # never mistaken for a CUDA-confirmed budget-adequacy diagnostic.
        raise SystemExit(
            "CUDA-enabled torch is required for the predeclared budget-"
            "adequacy diagnostic; aborting CPU run so a CPU result is not "
            "mistaken for a CUDA-confirmed outcome."
        )

    n_stations = len(stations)
    eval_start = 11

    init_pos_sigma = baseline_cfg.ukf.init_pos_std_m
    init_vel_sigma = baseline_cfg.ukf.init_vel_std_mps

    def _gen(rng: np.random.Generator, n: int) -> list[dict[str, np.ndarray]]:
        return [
            base._generate_one(
                rng,
                dataset_cfg.orbit_sampling,
                stations,
                dyn,
                meas_std,
                dataset_cfg.measurement_noise.outlier_prob,
                dataset_cfg.measurement_noise.outlier_scale,
                dataset_cfg.measurement_noise.random_dropout_prob,
                init_pos_sigma,
                init_vel_sigma,
            )
            for _ in range(n)
        ]

    print(f"[KNet-BA] device={device}, generating data", flush=True)
    t0 = time.perf_counter()
    train_rng = np.random.default_rng(train_seed)
    val_rng = np.random.default_rng(val_seed)
    test_rng = np.random.default_rng(test_seed)
    train_bundles = _gen(train_rng, n_train)
    cv_bundles = _gen(val_rng, n_cv)
    test_bundles = _gen(test_rng, n_test)
    t_gen = time.perf_counter() - t0

    train_input, train_target, train_vis, train_x0 = base._prepare_input_target(
        train_bundles, n_stations
    )
    cv_input, cv_target, cv_vis, cv_x0 = base._prepare_input_target(
        cv_bundles, n_stations
    )
    test_input, test_target, test_vis, test_x0 = base._prepare_input_target(
        test_bundles, n_stations
    )

    T = dyn.steps
    sys_funcs = base.SPOTODSystemFunctions(
        stations=stations,
        times_s=np.arange(T, dtype=np.float64) * dyn.dt_s,
        dt_s=dyn.dt_s,
        ballistic_coeff_m2_per_kg=dyn.ballistic_coeff_m2_per_kg,
        drag_rho_ref=dyn.drag_rho_ref,
        drag_h_ref_m=dyn.drag_h_ref_m,
        drag_scale_height_m=dyn.drag_scale_height_m,
    )
    m1x_0 = torch.zeros(6, 1)
    m2x_0 = torch.eye(6) * (init_pos_sigma ** 2)
    Q = torch.eye(6)
    R = torch.eye(sys_funcs.obs_dim)
    sys_model = base.SPOTODSystemModel(
        sys_funcs, T=T, T_test=T, m1x_0=m1x_0, m2x_0=m2x_0, Q=Q, R=R
    )

    knet = base.KNetSPOTODWrapper()

    class _Args:
        pass

    knet_args = _Args()
    knet_args.use_cuda = device.type == "cuda"
    knet_args.n_batch = max(n_batch, n_cv)
    knet_args.in_mult_KNet = in_mult
    knet_args.out_mult_KNet = out_mult
    knet.NNBuild(sys_model, knet_args)
    knet.attach_sys_funcs(sys_funcs)
    n_params = sum(p.numel() for p in knet.parameters() if p.requires_grad)
    print(
        f"[KNet-BA] params={n_params}, T={T}, m={sys_model.m}, n={sys_model.n}, "
        f"n_steps={n_steps}, snapshots={snapshot_steps}",
        flush=True,
    )

    t0 = time.perf_counter()
    train_out = _train_with_snapshots(
        knet=knet,
        sys_model=sys_model,
        sys_funcs=sys_funcs,
        train_input=train_input,
        train_target=train_target,
        train_vis=train_vis,
        train_x0=train_x0,
        cv_input=cv_input,
        cv_target=cv_target,
        cv_vis=cv_vis,
        cv_x0=cv_x0,
        n_steps=n_steps,
        n_batch=n_batch,
        lr=lr,
        wd=wd,
        device=device,
        eval_start=eval_start,
        snapshot_steps=snapshot_steps,
    )
    t_train = time.perf_counter() - t0

    states_all = np.stack([b["states"] for b in test_bundles], axis=0)
    meas_all = np.stack([b["measurements"] for b in test_bundles], axis=0)
    vis_all = np.stack([b["visibility"] for b in test_bundles], axis=0)
    times_all = np.tile(
        np.arange(T, dtype=np.float64) * dyn.dt_s, (len(test_bundles), 1)
    )
    x0_est_all = np.stack([b["x0_est"] for b in test_bundles], axis=0)

    ekf_kwargs = dict(
        ballistic_coeff_m2_per_kg=dyn.ballistic_coeff_m2_per_kg,
        drag_rho_ref=dyn.drag_rho_ref,
        drag_h_ref_m=dyn.drag_h_ref_m,
        drag_scale_height_m=dyn.drag_scale_height_m,
        enable_third_body=dyn.enable_third_body,
        enable_srp=dyn.enable_srp,
        srp_area_to_mass_m2_per_kg=dyn.srp_area_to_mass_m2_per_kg,
        srp_cr=dyn.srp_cr,
        sun_initial_phase_rad=dyn.sun_initial_phase_rad,
        moon_initial_phase_rad=dyn.moon_initial_phase_rad,
    )
    ekf_cfg = EKFConfig(
        q_pos_m=baseline_cfg.ekf.q_pos_m,
        q_vel_mps=baseline_cfg.ekf.q_vel_mps,
        init_pos_std_m=baseline_cfg.ekf.init_pos_std_m,
        init_vel_std_mps=baseline_cfg.ekf.init_vel_std_mps,
        gating_threshold=baseline_cfg.ekf.gating_threshold,
        angle_deweight_elev_cap_deg=getattr(baseline_cfg.ekf, "angle_deweight_elev_cap_deg", None),
    )
    ukf_cfg = UKFConfig(
        q_pos_m=baseline_cfg.ukf.q_pos_m,
        q_vel_mps=baseline_cfg.ukf.q_vel_mps,
        init_pos_std_m=baseline_cfg.ukf.init_pos_std_m,
        init_vel_std_mps=baseline_cfg.ukf.init_vel_std_mps,
        alpha=baseline_cfg.ukf.alpha,
        beta=baseline_cfg.ukf.beta,
        kappa=baseline_cfg.ukf.kappa,
        angle_deweight_elev_cap_deg=getattr(baseline_cfg.ukf, "angle_deweight_elev_cap_deg", None),
    )
    aukf_cfg = AdaptiveUKFConfig(
        q_pos_m=baseline_cfg.aukf.q_pos_m,
        q_vel_mps=baseline_cfg.aukf.q_vel_mps,
        init_pos_std_m=baseline_cfg.aukf.init_pos_std_m,
        init_vel_std_mps=baseline_cfg.aukf.init_vel_std_mps,
        alpha=baseline_cfg.aukf.alpha,
        beta=baseline_cfg.aukf.beta,
        kappa=baseline_cfg.aukf.kappa,
        adapt_rate=baseline_cfg.aukf.adapt_rate,
        min_r_scale=baseline_cfg.aukf.min_r_scale,
        max_r_scale=baseline_cfg.aukf.max_r_scale,
        huber_kappa=baseline_cfg.aukf.huber_kappa,
        nis_soft_gate=baseline_cfg.aukf.nis_soft_gate,
        angle_deweight_elev_cap_deg=getattr(baseline_cfg.aukf, "angle_deweight_elev_cap_deg", None),
    )
    pukf_cfg = ProcessNoiseAdaptiveUKFConfig(
        q_pos_m=baseline_cfg.ukf.q_pos_m,
        q_vel_mps=baseline_cfg.ukf.q_vel_mps,
        init_pos_std_m=baseline_cfg.ukf.init_pos_std_m,
        init_vel_std_mps=baseline_cfg.ukf.init_vel_std_mps,
        alpha=baseline_cfg.ukf.alpha,
        beta=baseline_cfg.ukf.beta,
        kappa=baseline_cfg.ukf.kappa,
        window_size=int(th["window_size"]),
        nis_per_update_expected=float(th["nis_per_update_expected"]),
        nis_warn_ratio=float(th["nis_warn_ratio"]),
        nis_alarm_ratio=float(th["nis_alarm_ratio"]),
        q_scale_warn=float(th["q_scale_warn"]),
        q_scale_alarm=float(th["q_scale_alarm"]),
        q_scale_max=float(th["q_scale_max"]),
        smoothing=float(th["smoothing"]),
        angle_deweight_elev_cap_deg=getattr(baseline_cfg.ukf, "angle_deweight_elev_cap_deg", None),
    )

    ekf_pred = np.zeros_like(states_all)
    ukf_pred = np.zeros_like(states_all)
    aukf_pred = np.zeros_like(states_all)
    pukf_pred = np.zeros_like(states_all)
    for i in range(len(test_bundles)):
        ekf_pred[i], _ = run_ekf(
            measurements=meas_all[i],
            visibility=vis_all[i],
            times_s=times_all[i],
            stations=stations,
            meas_std_vector=meas_std,
            x0_est=x0_est_all[i],
            cfg=ekf_cfg,
            **ekf_kwargs,
        )
        ukf_pred[i], _ = run_ukf(
            measurements=meas_all[i],
            visibility=vis_all[i],
            times_s=times_all[i],
            stations=stations,
            meas_std_vector=meas_std,
            x0_est=x0_est_all[i],
            cfg=ukf_cfg,
            **ekf_kwargs,
        )
        aukf_pred[i], _ = run_adaptive_ukf(
            measurements=meas_all[i],
            visibility=vis_all[i],
            times_s=times_all[i],
            stations=stations,
            meas_std_vector=meas_std,
            x0_est=x0_est_all[i],
            cfg=aukf_cfg,
            **ekf_kwargs,
        )
        pukf_pred[i], _, _ = run_process_noise_adaptive_ukf(
            measurements=meas_all[i],
            visibility=vis_all[i],
            times_s=times_all[i],
            stations=stations,
            meas_std_vector=meas_std,
            x0_est=x0_est_all[i],
            cfg=pukf_cfg,
            **ekf_kwargs,
        )
    classical_rmse = {
        "EKF": base._per_traj_observed_pos_rmse(states_all, ekf_pred, vis_all, eval_start),
        "UKF": base._per_traj_observed_pos_rmse(states_all, ukf_pred, vis_all, eval_start),
        "AUKF": base._per_traj_observed_pos_rmse(states_all, aukf_pred, vis_all, eval_start),
        "PUKF": base._per_traj_observed_pos_rmse(states_all, pukf_pred, vis_all, eval_start),
    }
    classical_means = {k: float(np.nanmean(v)) for k, v in classical_rmse.items()}
    best_classical_name = min(classical_means, key=lambda k: classical_means[k])
    best_classical_mean = classical_means[best_classical_name]
    practical_floor_pct = 3.0
    practical_floor_m = practical_floor_pct / 100.0 * best_classical_mean

    snapshots_payload: list[dict[str, Any]] = []
    snapshots_state = train_out["snapshots"]
    per_traj_rows: list[dict[str, Any]] = []
    for step in snapshot_steps:
        state_dict = snapshots_state.get(int(step))
        if state_dict is None:
            continue
        per_traj = _eval_snapshot(
            knet,
            sys_funcs,
            state_dict,
            test_input,
            test_vis,
            test_x0,
            device,
            T,
            sys_model.m,
            states_all,
            vis_all,
            eval_start,
        )
        diffs = per_traj - classical_rmse[best_classical_name]
        mean_d, lo, hi = base._paired_bootstrap_ci(
            diffs, n_boot=3000, seed=test_seed + step
        )
        finite = diffs[np.isfinite(diffs)]
        knet_mean = float(np.nanmean(per_traj))
        knet_is_strictly_lowest = knet_mean < min(classical_means.values())
        ci_strictly_negative = hi < 0.0
        floor_exceeded = (-mean_d > practical_floor_m) and (mean_d < 0.0)
        is_positive = bool(
            knet_is_strictly_lowest and ci_strictly_negative and floor_exceeded
        )
        snapshots_payload.append(
            {
                "optimizer_step": int(step),
                "validation_mse_at_snapshot": float(train_out["snapshot_cv"].get(int(step), float("nan"))),
                "train_mse_at_snapshot": float(train_out["snapshot_train"].get(int(step), float("nan"))),
                "test_observed_step_rmse_mean_m": knet_mean,
                "test_observed_step_rmse_median_m": float(np.nanmedian(per_traj)),
                "best_classical_name": best_classical_name,
                "best_classical_mean_m": best_classical_mean,
                "knet_minus_best_mean_m": mean_d,
                "knet_minus_best_ci_lo_m": lo,
                "knet_minus_best_ci_hi_m": hi,
                "knet_better_count": int(np.sum(finite < 0.0)) if finite.size else 0,
                "n_paired": int(finite.size),
                "predeclared_positive_criterion_met": is_positive,
                "knet_is_strictly_lowest_mean": bool(knet_is_strictly_lowest),
                "ci_strictly_negative_for_knet": bool(ci_strictly_negative),
                "floor_exceeded": bool(floor_exceeded),
            }
        )
        for traj_idx in range(states_all.shape[0]):
            per_traj_rows.append(
                {
                    "optimizer_step": int(step),
                    "trajectory_index": traj_idx,
                    "test_observed_step_pos_rmse_m": float(per_traj[traj_idx])
                    if np.isfinite(per_traj[traj_idx])
                    else None,
                }
            )
    for traj_idx in range(states_all.shape[0]):
        per_traj_rows.append(
            {
                "optimizer_step": -1,
                "trajectory_index": traj_idx,
                "EKF_pos_rmse_m": float(classical_rmse["EKF"][traj_idx])
                if np.isfinite(classical_rmse["EKF"][traj_idx])
                else None,
                "UKF_pos_rmse_m": float(classical_rmse["UKF"][traj_idx])
                if np.isfinite(classical_rmse["UKF"][traj_idx])
                else None,
                "AUKF_pos_rmse_m": float(classical_rmse["AUKF"][traj_idx])
                if np.isfinite(classical_rmse["AUKF"][traj_idx])
                else None,
                "PUKF_pos_rmse_m": float(classical_rmse["PUKF"][traj_idx])
                if np.isfinite(classical_rmse["PUKF"][traj_idx])
                else None,
            }
        )

    # Validation-best-snapshot informational selector.
    val_mses = [(s["optimizer_step"], s["validation_mse_at_snapshot"]) for s in snapshots_payload]
    val_best = min(val_mses, key=lambda kv: kv[1]) if val_mses else (None, None)
    summary = {
        "validation_best_snapshot_step": int(val_best[0]) if val_best[0] is not None else None,
        "validation_best_snapshot_mse": float(val_best[1]) if val_best[1] is not None else None,
    }
    if val_best[0] is not None:
        for s in snapshots_payload:
            if s["optimizer_step"] == val_best[0]:
                summary["validation_best_test_mean_m"] = s["test_observed_step_rmse_mean_m"]
                summary["validation_best_predeclared_positive_criterion_met"] = s[
                    "predeclared_positive_criterion_met"
                ]
                break

    # Learning-curve interpretation: descend ratio between first and last
    # predeclared snapshot. If the descent ratio is below a small threshold,
    # we interpret the curve as a plateau under the predeclared budget; if
    # it remains large, we interpret it as modestly descending under additional
    # budget rather than practically closeable. The threshold below is informational only and does not enter
    # the predeclared decision predicate.
    descent_ratio = None
    if len(snapshots_payload) >= 2:
        first_test = snapshots_payload[0]["test_observed_step_rmse_mean_m"]
        last_test = snapshots_payload[-1]["test_observed_step_rmse_mean_m"]
        if first_test > 0:
            descent_ratio = float((first_test - last_test) / first_test)
    summary["descent_ratio_first_to_last_snapshot"] = descent_ratio
    summary["informational_plateau_threshold_descent_ratio"] = 0.05
    if descent_ratio is not None:
        summary["informational_interpretation"] = (
            "plateau_under_predeclared_schedule"
            if descent_ratio <= 0.05
            else "modestly_descending_not_practically_closeable"
        )

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    payload: dict[str, Any] = {
        "schema_version": "kalmannet_spot_od_budget_adequacy_v1",
        "scenario": "kalmannet_spot_od_budget_adequacy_loop58",
        "vendor_commit": base.VENDOR_COMMIT,
        "device": str(device),
        "n_params_kalmannet": int(n_params),
        "config": {
            "n_train": int(n_train),
            "n_cv": int(n_cv),
            "n_test": int(n_test),
            "n_steps_total": int(n_steps),
            "snapshot_steps": [int(s) for s in snapshot_steps],
            "n_batch": int(n_batch),
            "lr": float(lr),
            "wd": float(wd),
            "in_mult": int(in_mult),
            "out_mult": int(out_mult),
            "train_seed": int(train_seed),
            "val_seed": int(val_seed),
            "test_seed": int(test_seed),
            "T": int(T),
            "m": int(sys_model.m),
            "n": int(sys_model.n),
            "eval_start_step": int(eval_start),
            "practical_floor_pct": practical_floor_pct,
            "practical_floor_m_absolute": practical_floor_m,
        },
        "classical_baselines_mean_observed_step_rmse_m": classical_means,
        "best_classical_baseline": best_classical_name,
        "snapshots": snapshots_payload,
        "summary": summary,
        "training_history_summary": {
            "n_logged_steps": len(train_out["history"]),
            "final_train_mse": float(train_out["history"][-1]["train_mse"]) if train_out["history"] else None,
            "final_cv_mse": float(train_out["history"][-1]["cv_mse"]) if train_out["history"] else None,
            "best_cv_mse": float(train_out["best_cv"]),
        },
        "elapsed_seconds": {
            "data_generation": float(t_gen),
            "training": float(t_train),
        },
        "predeclared_rule_path": args.predeclared_rule,
        "predeclared_rule_digest_sha256": hashlib.sha256(
            Path(args.predeclared_rule).read_bytes()
        ).hexdigest(),
    }

    payload["training_history"] = train_out["history"]
    out_json = out_dir / "kalmannet_spot_od_budget_adequacy.json"
    out_json.write_text(json.dumps(payload, indent=2, default=float))
    pd.DataFrame(per_traj_rows).to_csv(
        out_dir / "kalmannet_spot_od_budget_adequacy.csv", index=False
    )

    print(
        json.dumps(
            {
                "snapshots_summary": [
                    {
                        "step": s["optimizer_step"],
                        "cv_mse": s["validation_mse_at_snapshot"],
                        "test_knet_mean_m": s["test_observed_step_rmse_mean_m"],
                        "best_classical_m": s["best_classical_mean_m"],
                        "gap_m": s["knet_minus_best_mean_m"],
                        "ci_lo": s["knet_minus_best_ci_lo_m"],
                        "ci_hi": s["knet_minus_best_ci_hi_m"],
                        "positive_criterion_met": s["predeclared_positive_criterion_met"],
                    }
                    for s in snapshots_payload
                ],
                "classical_means": classical_means,
                "summary": summary,
                "device": str(device),
                "vendor_commit": base.VENDOR_COMMIT,
                "elapsed_seconds": payload["elapsed_seconds"],
            },
            indent=2,
            default=float,
        ),
        flush=True,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
