#!/usr/bin/env python
"""KalmanNet SPOT-OD design-gap addressing sensitivity (Loop 52).

This is a POST-REVIEW, PRE-RUN external-comparator sensitivity. The
faithful KalmanNet SPOT-OD re-instantiation reported in the manuscript
explicitly does NOT apply four design choices identified up-front in
the supplement:

  (1) Orbital-scale state/observation normalization
  (2) Sequence-length and curriculum rematching
  (3) Sparse-observation architectural adaptation
  (4) Learning-rate and budget recalibration

This driver runs the same upstream KalmanNet architecture with all four
addressed simultaneously, so the re-instantiation gap is no longer
ascribable to those four scoped-out choices. The predeclared rule
artefact for this sensitivity is

  release/predeclarations/kalmannet_design_gap_sensitivity_loop52.json

Per that artefact the comparator is reported as a single sensitivity at
one budget and seed split; it does not alter, replace, or supersede the
primary predeclared audit, and any outcome (positive / inconclusive /
negative) is reported as a bounded sensitivity.

Outputs (non-paper-facing JSON/CSV):
  results/kalmannet_spot_od/design_gap_sensitivity.json
  results/kalmannet_spot_od/design_gap_sensitivity.csv

Paper-facing table is generated by build_paper_assets.py from the JSON.
"""
from __future__ import annotations

try:
    from _bootstrap import ensure_src_on_path
except ModuleNotFoundError:  # pragma: no cover
    from scripts._bootstrap import ensure_src_on_path

ensure_src_on_path()

import argparse
import hashlib
import json
import math
import time
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

# Reuse the faithful transposition driver for data generation, system
# functions, training stack, and per-trajectory RMSE/bootstrap helpers.
import run_kalmannet_spot_od_transposition as base
import run_kalmannet_spot_od_diagnostic as dc

import torch  # noqa: E402
import torch.nn as nn  # noqa: E402

from gnn_state_estimation.dataset import MEAS_SCALE, STATE_SCALE  # noqa: E402
from gnn_state_estimation.evaluation import parse_baseline_config  # noqa: E402
from gnn_state_estimation.filters import (  # noqa: E402
    EKFConfig,
    UKFConfig,
    AdaptiveUKFConfig,
    ProcessNoiseAdaptiveUKFConfig,
    run_ekf,
    run_ukf,
    run_adaptive_ukf,
    run_process_noise_adaptive_ukf,
)
from gnn_state_estimation.simulation import parse_dataset_config  # noqa: E402
from gnn_state_estimation.utils.io import load_yaml  # noqa: E402


# --- Noise-equivalent observation normalization (Design gap 1) -----------


def _compute_noise_equivalent_scale(
    meas_std_vector: np.ndarray, n_stations: int
) -> np.ndarray:
    """Per-channel divisor that brings the line-of-sight measurement-noise
    standard deviation to unit scale in the SCALED observation coordinates.

    The existing MEAS_SCALE convention divides each LoS channel by a fixed
    constant (range / 1e7 m, az / pi, el / pi/2, range-rate / 1e4 m/s); in
    those scaled coordinates the per-channel measurement-noise standard
    deviations are heterogeneous (range channel ~3e-6, angle channels ~1e-4,
    range-rate ~8e-6). The upstream KalmanNet linear-canonical benchmark
    assumes unit-scale innovation noise; this divisor restores that on the
    SPOT-OD measurement model. The divisor uses the documented measurement
    noise standard deviations from the experiment configuration, NOT any
    train-set statistics, so it is deterministic given the configuration.

    Returns: shape (4*n_stations,), one positive divisor per LoS channel.
    """
    base = meas_std_vector / MEAS_SCALE  # (4,) per-station scaled noise std
    base = np.clip(base, 1e-12, None)
    return np.tile(base, n_stations)


def _apply_noise_equivalent_norm(
    obs: torch.Tensor, scale: torch.Tensor, vis: torch.Tensor, n_stations: int
) -> torch.Tensor:
    """Divide each LoS channel by its noise-equivalent scale; preserve the
    invisible-channel zero-pad and the visibility-flag block.

    obs shape: (N, 4*S+S, T); vis shape: (N, S, T).
    """
    out = obs.clone()
    obs_block = out[:, : 4 * n_stations, :]  # (N, 4*S, T)
    vis_per_channel = vis.unsqueeze(2).expand(-1, -1, 4, -1).reshape(
        obs.shape[0], 4 * n_stations, obs.shape[-1]
    )
    normed = obs_block / scale[: 4 * n_stations].view(1, -1, 1)
    # Invisible entries are zero in input; division leaves them zero; we
    # multiply by the visibility mask to be defensive against any divisor
    # interaction with stray non-zero invisible entries.
    out[:, : 4 * n_stations, :] = normed * vis_per_channel
    return out


# --- Noise-equivalent visibility-augmented system functions (Gaps 1+3) ----


class NoiseEquivalentVisibilityAugmentedSystemFunctions(dc.VisibilityAugmentedSPOTODSystemFunctions):
    """System functions that emit the noise-equivalent-normalized
    visibility-augmented observation block so h(x) sees the same channel
    scale as the input feed. The invisible-channel zero-pad convention is
    preserved: invisible blocks are zero in BOTH the observation and the
    predicted observation, so the innovation is exactly zero on invisible
    channels by construction. The visibility-flag block is unchanged.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._scale: np.ndarray | None = None

    def attach_noise_scale(self, scale: torch.Tensor) -> None:
        self._scale = scale.detach().cpu().numpy().astype(np.float64)

    def f_torch(self, x: torch.Tensor) -> torch.Tensor:
        # Clamp the scaled state into a physically plausible band before the
        # numerical propagator so a transient bad gain cannot drive the
        # propagator through overflow. Positions are divided by 1e7 m and
        # velocities by 1e4 m/s, so |x| at most ~1 for LEO; band of 2.0
        # admits any plausible LEO state but excludes pathological divergence.
        x_clamped = torch.clamp(x, min=-2.0, max=2.0)
        return super().f_torch(x_clamped)

    def h_torch(self, x: torch.Tensor) -> torch.Tensor:
        out = super().h_torch(x)  # zero-padded visibility-augmented
        if self._scale is None:
            return out
        device = out.device
        dtype = out.dtype
        was_2d = out.dim() == 2
        if was_2d:
            out = out.unsqueeze(0)
        out_np = out.detach().cpu().numpy()
        n_st = self.n_stations
        out_np[:, : 4 * n_st, 0] = out_np[:, : 4 * n_st, 0] / self._scale[: 4 * n_st]
        t_out = torch.from_numpy(out_np).to(device=device, dtype=dtype)
        if was_2d:
            t_out = t_out.squeeze(0)
        return t_out


# --- Visibility-gated KalmanNet wrapper (Design gap 3, part b) ------------


class VisibilityGatedKNetWrapper(base.KNetSPOTODWrapper):
    """At zero-visibility steps the learned correction is force-gated to the
    prior prediction. The underlying KalmanNet gain still runs (its hidden
    state continues to evolve) but its output state estimate is replaced by
    the prior so the learned correction cannot act on open-loop propagation
    steps. Implements design gap 3, part (b)."""

    def attach_step_visibility(self, step_visibility: np.ndarray) -> None:
        # Boolean visibility per (batch, T) — 1 means at least one station
        # visible at that step. Used inside the training/predict loops.
        self._step_visibility = np.asarray(step_visibility, dtype=np.float64)

    def gate_with_prior(self, x_post: torch.Tensor, x_prior: torch.Tensor, batch_visible: torch.Tensor) -> torch.Tensor:
        """Return x_post on visible steps and x_prior on invisible steps.

        batch_visible shape: (B,) 0/1 visibility flag for the current step.
        """
        b = x_post.shape[0]
        mask = batch_visible.view(b, 1, 1).to(x_post.device).to(x_post.dtype)
        return mask * x_post + (1.0 - mask) * x_prior


# --- Two-stage visibility-stratified curriculum (Design gap 2) -----------


def _select_high_visibility_indices(
    train_vis: torch.Tensor, eval_start: int, tercile: float = 1.0 / 3.0
) -> np.ndarray:
    """Return indices of the top-tercile training trajectories by per-trajectory
    visibility fraction over the evaluation window.

    train_vis shape: (N, S, T). Visibility fraction is the fraction of
    eval-window steps with at least one visible station.
    """
    vis_per_step = (train_vis.sum(dim=1) > 0.5).float()  # (N, T)
    frac = vis_per_step[:, eval_start:].mean(dim=1).cpu().numpy()
    n = frac.shape[0]
    k = max(1, int(math.ceil(tercile * n)))
    return np.argsort(-frac)[:k]


# --- Cosine schedule with warm-up (Design gap 4) -------------------------


def _cosine_lr(step: int, total: int, base_lr: float, warmup_frac: float) -> float:
    warm = max(1, int(round(warmup_frac * total)))
    if step <= warm:
        return base_lr * step / warm
    progress = (step - warm) / max(1, total - warm)
    return 0.5 * base_lr * (1.0 + math.cos(math.pi * progress))


# --- Hardened training loop ----------------------------------------------


def _train_hardened(
    knet: VisibilityGatedKNetWrapper,
    sys_funcs: StandardizedVisibilityAugmentedSystemFunctions,
    train_input: torch.Tensor,
    train_target: torch.Tensor,
    train_vis: torch.Tensor,
    train_x0: torch.Tensor,
    cv_input: torch.Tensor,
    cv_target: torch.Tensor,
    cv_vis: torch.Tensor,
    cv_x0: torch.Tensor,
    *,
    m: int,
    n_steps: int,
    warmup_steps: int,
    curriculum_stage_a_steps: int,
    n_batch: int,
    base_lr: float,
    wd: float,
    device: torch.device,
    eval_start: int,
    cv_every: int,
) -> dict[str, Any]:
    """Hardened training loop that addresses all four design gaps."""
    knet.to(device)
    optimizer = torch.optim.Adam(knet.parameters(), lr=base_lr, weight_decay=wd)
    loss_fn = nn.MSELoss(reduction="mean")
    best_cv = float("inf")
    best_state = None
    history: list[dict[str, Any]] = []
    n_train = train_input.shape[0]
    n_cv = cv_input.shape[0]
    T = train_input.shape[-1]

    # Design gap 2: stage A trains only on the top-tercile-visibility subset.
    stage_a_indices = _select_high_visibility_indices(train_vis, eval_start)
    print(f"[KNet-DG] curriculum stage A indices: {len(stage_a_indices)}/{n_train}", flush=True)

    # Precompute per-trajectory per-step visibility (>=1 station visible).
    train_step_vis = (train_vis.sum(dim=1) > 0.5).float().cpu().numpy()  # (N, T)
    cv_step_vis = (cv_vis.sum(dim=1) > 0.5).float().cpu().numpy()  # (Ncv, T)

    rng_py = np.random.default_rng(0)
    last_cv = float("inf")
    for step_i in range(1, n_steps + 1):
        if step_i <= curriculum_stage_a_steps:
            pool = stage_a_indices
            stage_label = "A"
        else:
            pool = np.arange(n_train)
            stage_label = "B"
        bs = min(n_batch, pool.size)
        idx = rng_py.choice(pool, size=bs, replace=False)
        y_batch = train_input[idx].to(device)
        x_batch = train_target[idx].to(device)
        v_batch = train_vis[idx].to(device)
        x0_batch = train_x0[idx].to(device)
        sv_batch = train_step_vis[idx]  # (bs, T)
        b = y_batch.shape[0]

        # Cosine LR schedule (design gap 4).
        lr_t = _cosine_lr(step_i, n_steps, base_lr, warmup_frac=max(1e-6, warmup_steps / n_steps))
        for g in optimizer.param_groups:
            g["lr"] = lr_t

        knet.train()
        knet.batch_size = b
        knet.init_hidden_KNet()
        sys_funcs.visibility_mask = None
        sys_funcs.step_idx = 0
        knet.InitSequence(x0_batch, T)
        sys_funcs.reset()

        x_out = torch.zeros((b, m, T), device=device, dtype=y_batch.dtype)
        x_prev = x0_batch.squeeze(2)
        for t in range(T):
            sys_funcs.step_idx = t
            sys_funcs.set_visibility(v_batch[:, :, t].detach().cpu().numpy())
            y_t = y_batch[:, :, t].unsqueeze(2)
            # Compute prior prediction for gating: propagate x_prev one step
            # with the wrapper f (no learning).
            with torch.no_grad():
                x_prior_pred = sys_funcs.f_torch(x_prev.unsqueeze(2)).squeeze(2)
            x_t = knet(y_t).squeeze(2)
            batch_vis_t = torch.from_numpy(sv_batch[:, t]).to(device).to(x_t.dtype)
            # Design gap 3(b): force-gate learned correction at zero visibility.
            x_t = knet.gate_with_prior(x_t.unsqueeze(2), x_prior_pred.unsqueeze(2), batch_vis_t).squeeze(2)
            x_out[:, :, t] = x_t
            x_prev = x_t

        # Position+velocity loss (state loss, like upstream KalmanNet does
        # on its native benchmark) over the eval window.
        loss_pos = loss_fn(x_out[:, :3, eval_start:], x_batch[:, :3, eval_start:])
        loss_vel = loss_fn(x_out[:, 3:, eval_start:], x_batch[:, 3:, eval_start:])
        loss = loss_pos + loss_vel
        optimizer.zero_grad()
        if not torch.isfinite(loss):
            train_loss = float("inf")
            grad_norm = float("nan")
        else:
            loss.backward(retain_graph=False)
            grad_norm = float(
                torch.nn.utils.clip_grad_norm_(knet.parameters(), max_norm=1.0).item()
            )
            optimizer.step()
            train_loss = float(loss.item())

        # CV every cv_every steps (or last step). Saves cost vs every step.
        run_cv = (step_i % cv_every == 0) or (step_i == n_steps) or (step_i == 1)
        if run_cv:
            knet.eval()
            knet.batch_size = n_cv
            knet.init_hidden_KNet()
            sys_funcs.visibility_mask = None
            sys_funcs.step_idx = 0
            knet.InitSequence(cv_x0.to(device), T)
            sys_funcs.reset()
            with torch.no_grad():
                x_cv = torch.zeros((n_cv, m, T), device=device, dtype=cv_input.dtype)
                x_prev = cv_x0.to(device).squeeze(2)
                for t in range(T):
                    sys_funcs.step_idx = t
                    sys_funcs.set_visibility(cv_vis[:, :, t].detach().cpu().numpy())
                    y_t = cv_input[:, :, t].to(device).unsqueeze(2)
                    x_prior_pred = sys_funcs.f_torch(x_prev.unsqueeze(2)).squeeze(2)
                    x_t = knet(y_t).squeeze(2)
                    batch_vis_t = torch.from_numpy(cv_step_vis[:, t]).to(device).to(x_t.dtype)
                    x_t = knet.gate_with_prior(x_t.unsqueeze(2), x_prior_pred.unsqueeze(2), batch_vis_t).squeeze(2)
                    x_cv[:, :, t] = x_t
                    x_prev = x_t
                cv_pos = float(
                    loss_fn(x_cv[:, :3, eval_start:], cv_target[:, :3, eval_start:].to(device)).item()
                )
                cv_vel = float(
                    loss_fn(x_cv[:, 3:, eval_start:], cv_target[:, 3:, eval_start:].to(device)).item()
                )
                cv_loss = cv_pos + cv_vel
            last_cv = cv_loss
            if cv_loss < best_cv:
                best_cv = cv_loss
                best_state = {k: v.clone().detach().cpu() for k, v in knet.state_dict().items()}
        else:
            cv_loss = last_cv

        history.append(
            {
                "step": step_i,
                "stage": stage_label,
                "lr": lr_t,
                "train_mse": train_loss,
                "cv_mse": cv_loss,
                "grad_norm": grad_norm,
            }
        )

        if step_i % 25 == 0 or step_i == 1 or step_i == n_steps:
            print(
                f"[KNet-DG] step {step_i} stage={stage_label} lr={lr_t:.3e} "
                f"train_mse={train_loss:.6f} cv_mse={cv_loss:.6f} best={best_cv:.6f}",
                flush=True,
            )

    if best_state is not None:
        knet.load_state_dict(best_state)
    return {"history": history, "best_cv": best_cv}


# --- Prediction with visibility-gating ------------------------------------


def _predict_hardened(
    knet: VisibilityGatedKNetWrapper,
    sys_funcs: StandardizedVisibilityAugmentedSystemFunctions,
    test_input: torch.Tensor,
    test_vis: torch.Tensor,
    test_x0: torch.Tensor,
    device: torch.device,
    T: int,
    m: int,
) -> np.ndarray:
    knet.eval()
    n = test_input.shape[0]
    knet.batch_size = n
    knet.init_hidden_KNet()
    sys_funcs.visibility_mask = None
    sys_funcs.step_idx = 0
    knet.InitSequence(test_x0.to(device), T)
    sys_funcs.reset()
    test_step_vis = (test_vis.sum(dim=1) > 0.5).float().cpu().numpy()  # (n, T)
    with torch.no_grad():
        out = torch.zeros((n, m, T), device=device, dtype=test_input.dtype)
        x_prev = test_x0.to(device).squeeze(2)
        for t in range(T):
            sys_funcs.step_idx = t
            sys_funcs.set_visibility(test_vis[:, :, t].detach().cpu().numpy())
            y_t = test_input[:, :, t].to(device).unsqueeze(2)
            x_prior_pred = sys_funcs.f_torch(x_prev.unsqueeze(2)).squeeze(2)
            x_t = knet(y_t).squeeze(2)
            batch_vis_t = torch.from_numpy(test_step_vis[:, t]).to(device).to(x_t.dtype)
            x_t = knet.gate_with_prior(x_t.unsqueeze(2), x_prior_pred.unsqueeze(2), batch_vis_t).squeeze(2)
            out[:, :, t] = x_t
            x_prev = x_t
    arr = out.detach().cpu().numpy().transpose(0, 2, 1)  # (n, T, m) scaled
    return arr * STATE_SCALE.astype(arr.dtype)


# --- Main -----------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--config", default="configs/experiment.yaml")
    p.add_argument(
        "--predeclared-rule",
        default="release/predeclarations/kalmannet_design_gap_sensitivity_loop52.json",
    )
    p.add_argument("--pukf-rule", default="release/predeclarations/pukf_q_adaptive_rule_loop41.json")
    p.add_argument("--output-dir", default="results/kalmannet_spot_od")
    p.add_argument("--n-train", type=int, default=120)
    p.add_argument("--n-cv", type=int, default=24)
    p.add_argument("--n-test", type=int, default=32)
    p.add_argument("--n-steps", type=int, default=1000)
    p.add_argument("--warmup-steps", type=int, default=100)
    p.add_argument("--curriculum-stage-a-steps", type=int, default=200)
    p.add_argument("--n-batch", type=int, default=24)
    p.add_argument("--base-lr", type=float, default=2e-4)
    p.add_argument("--wd", type=float, default=1e-4)
    p.add_argument("--in-mult", type=int, default=5)
    p.add_argument("--out-mult", type=int, default=4)
    p.add_argument("--train-seed", type=int, default=20260601)
    p.add_argument("--test-seed", type=int, default=20260701)
    p.add_argument("--cv-every", type=int, default=10)
    p.add_argument("--bootstrap-samples", type=int, default=3000)
    p.add_argument("--device", default="auto")
    return p


def main() -> int:
    args = build_parser().parse_args()
    cfg = load_yaml(Path(args.config))
    dataset_cfg = parse_dataset_config(cfg["simulation"])
    dyn = dataset_cfg.dynamics
    stations = dataset_cfg.stations
    meas_std = dataset_cfg.measurement_noise.std_vector
    baseline_cfg = parse_baseline_config(cfg["baselines"])
    pukf_rule = json.loads(Path(args.pukf_rule).read_text())
    pukf_th = pukf_rule["thresholds"]

    device_str = args.device
    if device_str == "auto":
        device_str = "cuda" if torch.cuda.is_available() else "cpu"
    device = torch.device(device_str)

    n_stations = len(stations)
    eval_start = 11

    # --- Generate train/cv/test trajectories (same seeds as faithful) -----
    train_rng = np.random.default_rng(args.train_seed)
    test_rng = np.random.default_rng(args.test_seed)
    init_pos_sigma = baseline_cfg.ukf.init_pos_std_m
    init_vel_sigma = baseline_cfg.ukf.init_vel_std_mps

    def _gen(rng, n):
        return [
            base._generate_one(
                rng,
                dataset_cfg.orbit_sampling,
                stations,
                dyn,
                meas_std,
                dataset_cfg.measurement_noise.outlier_prob,
                dataset_cfg.measurement_noise.outlier_scale,
                dataset_cfg.measurement_noise.random_dropout_prob,
                init_pos_sigma,
                init_vel_sigma,
            )
            for _ in range(n)
        ]

    print(f"[KNet-DG] device={device}, generating data", flush=True)
    t0 = time.perf_counter()
    train_bundles = _gen(train_rng, args.n_train)
    cv_bundles = _gen(train_rng, args.n_cv)
    test_bundles = _gen(test_rng, args.n_test)
    t_gen = time.perf_counter() - t0

    # Visibility-augmented inputs (n=40) for design gap 3(a).
    train_input, train_target, train_vis, train_x0 = dc._prepare_input_target_augmented(
        train_bundles, n_stations
    )
    cv_input, cv_target, cv_vis, cv_x0 = dc._prepare_input_target_augmented(cv_bundles, n_stations)
    test_input, test_target, test_vis, test_x0 = dc._prepare_input_target_augmented(
        test_bundles, n_stations
    )

    # Design gap 1: noise-equivalent observation normalization using the
    # documented measurement-noise standard deviations.
    scale_arr = _compute_noise_equivalent_scale(meas_std, n_stations)
    scale = torch.from_numpy(scale_arr.astype(np.float32))
    train_input = _apply_noise_equivalent_norm(train_input, scale, train_vis, n_stations)
    cv_input = _apply_noise_equivalent_norm(cv_input, scale, cv_vis, n_stations)
    test_input = _apply_noise_equivalent_norm(test_input, scale, test_vis, n_stations)

    # --- Build hardened KalmanNet + system model ---
    T = dyn.steps
    sys_funcs = NoiseEquivalentVisibilityAugmentedSystemFunctions(
        stations=stations,
        times_s=np.arange(T, dtype=np.float64) * dyn.dt_s,
        dt_s=dyn.dt_s,
        ballistic_coeff_m2_per_kg=dyn.ballistic_coeff_m2_per_kg,
        drag_rho_ref=dyn.drag_rho_ref,
        drag_h_ref_m=dyn.drag_h_ref_m,
        drag_scale_height_m=dyn.drag_scale_height_m,
    )
    sys_funcs.attach_noise_scale(scale)
    m1x_0 = torch.zeros(6, 1)
    m2x_0 = torch.eye(6) * (init_pos_sigma ** 2)
    Q = torch.eye(6)
    R = torch.eye(sys_funcs.obs_dim)
    sys_model = base.SPOTODSystemModel(sys_funcs, T=T, T_test=T, m1x_0=m1x_0, m2x_0=m2x_0, Q=Q, R=R)

    knet = VisibilityGatedKNetWrapper()

    class _Args:
        pass

    knet_args = _Args()
    knet_args.use_cuda = device.type == "cuda"
    knet_args.n_batch = max(args.n_batch, args.n_cv)
    knet_args.in_mult_KNet = args.in_mult
    knet_args.out_mult_KNet = args.out_mult
    knet.NNBuild(sys_model, knet_args)
    knet.attach_sys_funcs(sys_funcs)
    n_params = sum(p.numel() for p in knet.parameters() if p.requires_grad)
    print(
        f"[KNet-DG] params={n_params}, T={T}, m={sys_model.m}, n={sys_model.n}",
        flush=True,
    )

    # --- Train ---
    t0 = time.perf_counter()
    train_out = _train_hardened(
        knet=knet,
        sys_funcs=sys_funcs,
        train_input=train_input,
        train_target=train_target,
        train_vis=train_vis,
        train_x0=train_x0,
        cv_input=cv_input,
        cv_target=cv_target,
        cv_vis=cv_vis,
        cv_x0=cv_x0,
        m=sys_model.m,
        n_steps=args.n_steps,
        warmup_steps=args.warmup_steps,
        curriculum_stage_a_steps=args.curriculum_stage_a_steps,
        n_batch=args.n_batch,
        base_lr=args.base_lr,
        wd=args.wd,
        device=device,
        eval_start=eval_start,
        cv_every=args.cv_every,
    )
    t_train = time.perf_counter() - t0

    # --- Predict on test ---
    knet.batch_size = test_input.shape[0]
    knet_pred = _predict_hardened(knet, sys_funcs, test_input, test_vis, test_x0, device, T, sys_model.m)

    # --- Classical references on the same test population -----------------
    states_all = np.stack([b["states"] for b in test_bundles], axis=0)
    meas_all = np.stack([b["measurements"] for b in test_bundles], axis=0)
    vis_all = np.stack([b["visibility"] for b in test_bundles], axis=0)
    times_all = np.tile(np.arange(T, dtype=np.float64) * dyn.dt_s, (len(test_bundles), 1))
    x0_est_all = np.stack([b["x0_est"] for b in test_bundles], axis=0)

    ekf_kwargs = dict(
        ballistic_coeff_m2_per_kg=dyn.ballistic_coeff_m2_per_kg,
        drag_rho_ref=dyn.drag_rho_ref,
        drag_h_ref_m=dyn.drag_h_ref_m,
        drag_scale_height_m=dyn.drag_scale_height_m,
        enable_third_body=dyn.enable_third_body,
        enable_srp=dyn.enable_srp,
        srp_area_to_mass_m2_per_kg=dyn.srp_area_to_mass_m2_per_kg,
        srp_cr=dyn.srp_cr,
        sun_initial_phase_rad=dyn.sun_initial_phase_rad,
        moon_initial_phase_rad=dyn.moon_initial_phase_rad,
    )
    ekf_cfg = EKFConfig(
        q_pos_m=baseline_cfg.ekf.q_pos_m,
        q_vel_mps=baseline_cfg.ekf.q_vel_mps,
        init_pos_std_m=baseline_cfg.ekf.init_pos_std_m,
        init_vel_std_mps=baseline_cfg.ekf.init_vel_std_mps,
        gating_threshold=baseline_cfg.ekf.gating_threshold,
        angle_deweight_elev_cap_deg=getattr(baseline_cfg.ekf, "angle_deweight_elev_cap_deg", None),
    )
    ukf_cfg = UKFConfig(
        q_pos_m=baseline_cfg.ukf.q_pos_m,
        q_vel_mps=baseline_cfg.ukf.q_vel_mps,
        init_pos_std_m=baseline_cfg.ukf.init_pos_std_m,
        init_vel_std_mps=baseline_cfg.ukf.init_vel_std_mps,
        alpha=baseline_cfg.ukf.alpha,
        beta=baseline_cfg.ukf.beta,
        kappa=baseline_cfg.ukf.kappa,
        angle_deweight_elev_cap_deg=getattr(baseline_cfg.ukf, "angle_deweight_elev_cap_deg", None),
    )
    aukf_cfg = AdaptiveUKFConfig(
        q_pos_m=baseline_cfg.aukf.q_pos_m,
        q_vel_mps=baseline_cfg.aukf.q_vel_mps,
        init_pos_std_m=baseline_cfg.aukf.init_pos_std_m,
        init_vel_std_mps=baseline_cfg.aukf.init_vel_std_mps,
        alpha=baseline_cfg.aukf.alpha,
        beta=baseline_cfg.aukf.beta,
        kappa=baseline_cfg.aukf.kappa,
        adapt_rate=baseline_cfg.aukf.adapt_rate,
        min_r_scale=baseline_cfg.aukf.min_r_scale,
        max_r_scale=baseline_cfg.aukf.max_r_scale,
        huber_kappa=baseline_cfg.aukf.huber_kappa,
        nis_soft_gate=baseline_cfg.aukf.nis_soft_gate,
        angle_deweight_elev_cap_deg=getattr(baseline_cfg.aukf, "angle_deweight_elev_cap_deg", None),
    )
    pukf_cfg = ProcessNoiseAdaptiveUKFConfig(
        q_pos_m=baseline_cfg.ukf.q_pos_m,
        q_vel_mps=baseline_cfg.ukf.q_vel_mps,
        init_pos_std_m=baseline_cfg.ukf.init_pos_std_m,
        init_vel_std_mps=baseline_cfg.ukf.init_vel_std_mps,
        alpha=baseline_cfg.ukf.alpha,
        beta=baseline_cfg.ukf.beta,
        kappa=baseline_cfg.ukf.kappa,
        window_size=int(pukf_th["window_size"]),
        nis_per_update_expected=float(pukf_th["nis_per_update_expected"]),
        nis_warn_ratio=float(pukf_th["nis_warn_ratio"]),
        nis_alarm_ratio=float(pukf_th["nis_alarm_ratio"]),
        q_scale_warn=float(pukf_th["q_scale_warn"]),
        q_scale_alarm=float(pukf_th["q_scale_alarm"]),
        q_scale_max=float(pukf_th["q_scale_max"]),
        smoothing=float(pukf_th["smoothing"]),
        angle_deweight_elev_cap_deg=getattr(baseline_cfg.ukf, "angle_deweight_elev_cap_deg", None),
    )

    ekf_pred = np.zeros_like(states_all)
    ukf_pred = np.zeros_like(states_all)
    aukf_pred = np.zeros_like(states_all)
    pukf_pred = np.zeros_like(states_all)
    for i in range(len(test_bundles)):
        ekf_pred[i], _ = run_ekf(
            measurements=meas_all[i],
            visibility=vis_all[i],
            times_s=times_all[i],
            stations=stations,
            meas_std_vector=meas_std,
            x0_est=x0_est_all[i],
            cfg=ekf_cfg,
            **ekf_kwargs,
        )
        ukf_pred[i], _ = run_ukf(
            measurements=meas_all[i],
            visibility=vis_all[i],
            times_s=times_all[i],
            stations=stations,
            meas_std_vector=meas_std,
            x0_est=x0_est_all[i],
            cfg=ukf_cfg,
            **ekf_kwargs,
        )
        aukf_pred[i], _ = run_adaptive_ukf(
            measurements=meas_all[i],
            visibility=vis_all[i],
            times_s=times_all[i],
            stations=stations,
            meas_std_vector=meas_std,
            x0_est=x0_est_all[i],
            cfg=aukf_cfg,
            **ekf_kwargs,
        )
        pukf_pred[i], _, _ = run_process_noise_adaptive_ukf(
            measurements=meas_all[i],
            visibility=vis_all[i],
            times_s=times_all[i],
            stations=stations,
            meas_std_vector=meas_std,
            x0_est=x0_est_all[i],
            cfg=pukf_cfg,
            **ekf_kwargs,
        )

    metrics = {
        "KalmanNet-DesignGap": base._per_traj_observed_pos_rmse(
            states_all, knet_pred, vis_all, eval_start
        ),
        "EKF": base._per_traj_observed_pos_rmse(states_all, ekf_pred, vis_all, eval_start),
        "UKF": base._per_traj_observed_pos_rmse(states_all, ukf_pred, vis_all, eval_start),
        "AUKF": base._per_traj_observed_pos_rmse(states_all, aukf_pred, vis_all, eval_start),
        "PUKF": base._per_traj_observed_pos_rmse(states_all, pukf_pred, vis_all, eval_start),
    }
    means = {k: float(np.nanmean(v)) for k, v in metrics.items()}
    medians = {k: float(np.nanmedian(v)) for k, v in metrics.items()}

    classical_means = {k: v for k, v in means.items() if k != "KalmanNet-DesignGap"}
    best_classical = min(classical_means, key=lambda k: classical_means[k])
    diffs = metrics["KalmanNet-DesignGap"] - metrics[best_classical]
    mean_d, lo, hi = base._paired_bootstrap_ci(
        diffs, n_boot=int(args.bootstrap_samples), seed=args.test_seed
    )
    finite = diffs[np.isfinite(diffs)]
    paired = {
        "best_classical": best_classical,
        "best_classical_mean_m": float(classical_means[best_classical]),
        "mean_minus_best_m": float(mean_d),
        "ci_lo_m": float(lo),
        "ci_hi_m": float(hi),
        "n_paired": int(finite.size),
        "knet_better_count": int(np.sum(finite < 0.0)),
        "knet_better_rate_percent": float(100.0 * np.mean(finite < 0.0))
        if finite.size
        else float("nan"),
    }

    # Predeclared outcome classification.
    floor_pct = 3.0  # 3% practical-significance floor (matches manuscript-wide rule)
    floor_m = floor_pct / 100.0 * classical_means[best_classical]
    if not np.isfinite(lo) or not np.isfinite(hi):
        outcome = "indeterminate"
    elif lo > 0:
        outcome = "bounded_negative"
    elif hi < 0 and abs(mean_d) >= floor_m:
        outcome = "bounded_positive_above_floor"
    elif hi < 0:
        outcome = "bounded_positive_below_floor"
    else:
        outcome = "inconclusive_ci_contains_zero"

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    payload: dict[str, Any] = {
        "schema_version": "kalmannet_design_gap_sensitivity_v1",
        "scenario": "kalmannet_design_gap_sensitivity",
        "audit_category": "post_review_pre_run_external_comparator_sensitivity",
        "vendor_commit": base.VENDOR_COMMIT,
        "vendor_path": str(base.VENDOR_ROOT.relative_to(base.REPO_ROOT)),
        "device": str(device),
        "n_params_kalmannet": int(n_params),
        "config": {
            "n_train": int(args.n_train),
            "n_cv": int(args.n_cv),
            "n_test": int(args.n_test),
            "n_steps": int(args.n_steps),
            "warmup_steps": int(args.warmup_steps),
            "curriculum_stage_a_steps": int(args.curriculum_stage_a_steps),
            "n_batch": int(args.n_batch),
            "base_lr": float(args.base_lr),
            "wd": float(args.wd),
            "in_mult": int(args.in_mult),
            "out_mult": int(args.out_mult),
            "train_seed": int(args.train_seed),
            "test_seed": int(args.test_seed),
            "T": int(T),
            "m": int(sys_model.m),
            "n": int(sys_model.n),
            "eval_start_step": int(eval_start),
            "cv_every": int(args.cv_every),
        },
        "design_gaps_addressed": {
            "orbital_scale_normalization": True,
            "sequence_length_and_curriculum_rematching": True,
            "sparse_observation_architectural_adaptation": True,
            "learning_rate_and_budget_recalibration": True,
        },
        "classical_baselines_mean_observed_step_rmse_m": classical_means,
        "best_classical_baseline": best_classical,
        "elapsed_seconds": {
            "data_generation": float(t_gen),
            "training": float(t_train),
        },
        "training_history": train_out["history"],
        "best_cv_mse": float(train_out["best_cv"]),
        "observed_step_rmse_mean_m": means,
        "observed_step_rmse_median_m": medians,
        "paired_vs_best_classical": paired,
        "practical_significance_floor_percent": float(floor_pct),
        "practical_significance_floor_m": float(floor_m),
        "predeclared_outcome_class": outcome,
        "predeclared_rule_path": args.predeclared_rule,
        "predeclared_rule_digest_sha256": hashlib.sha256(
            Path(args.predeclared_rule).read_bytes()
        ).hexdigest(),
    }

    out_json = out_dir / "design_gap_sensitivity.json"
    out_json.write_text(json.dumps(payload, indent=2, default=float))

    rows = []
    for i in range(len(test_bundles)):
        row: dict[str, Any] = {"trajectory_index": i}
        for k, arr in metrics.items():
            row[f"{k}_observed_pos_rmse_m"] = float(arr[i]) if np.isfinite(arr[i]) else None
        rows.append(row)
    pd.DataFrame(rows).to_csv(out_dir / "design_gap_sensitivity.csv", index=False)

    print(json.dumps(
        {
            "observed_step_rmse_mean_m": means,
            "paired_vs_best_classical": paired,
            "predeclared_outcome_class": outcome,
            "device": str(device),
            "vendor_commit": base.VENDOR_COMMIT,
            "elapsed_seconds": payload["elapsed_seconds"],
        },
        indent=2,
        default=float,
    ))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
